---
- name: Check if CodeSniffer phpcs is globally installed
  stat:
    path: "{{ phpcs_binary }}"
  register: phpcs

- name: Install phpcs globally
  file:
    src: "{{ drupal_phpcs }}"
    dest: "{{ phpcs_binary }}"
    state: link
  when: phpcs.stat.exists == false

- name: Check if CodeSniffer phpcbf is globally installed
  stat:
    path: "{{ phpcbf_binary }}"
  register: phpcbf

- name: Install phpcbf globally
  file:
    src: "{{ drupal_phpcbf }}"
    dest: "{{ user_programs_path }}/phpcbf"
    state: link
  when: phpcbf.stat.exists == false

- name: Check if CodeSniffer bash aliases exist
  shell: grep -o 'MANAGED CODE SNIFFER BLOCK' {{ bashrc }} || echo "absent"
  register: codesniffer_aliases
  changed_when: codesniffer_aliases == "absent"

- name: Add CodeSniffer bash aliases
  blockinfile:
    dest: "{{ bashrc }}"
    block: |
      alias drupalcs="phpcs --standard=Drupal --extensions={{ codesniffer_extensions }}"
      alias drupalpractice="phpcs --standard=DrupalPractice --extensions={{ codesniffer_extensions }}"
      alias drupalfix="phpcbf --standard=Drupal --extensions={{ codesniffer_extensions }}"
    insertafter: EOF
    marker: "# {mark} MANAGED CODE SNIFFER BLOCK"
  when: codesniffer_aliases.stdout == 'absent'

- name: Register Drupal and DrupalPractice with PHPCS
  command: phpcs --config-set installed_paths {{ codesniffer_sniffs }}
  when: phpcs.stat.exists == false
