---
- name: Check if Drush is installed
  stat:
    path: "{{ drush_binary }}"
  register: drush_check

- name: Check if Drush can be updated
  command: date -r "{{ drush_binary }}" +%F
  register: outdated_drush
  when: drush_check.stat.exists == true
  changed_when: false

- set_fact:
    ansible_date: "{{ ansible_date_time.date }}"

- name: Install Drush globally
  get_url:
    url: "{{ drush_download_link }}"
    dest: "{{ drush_binary }}"
    force: yes
    mode: 0755
    validate_certs: no
  register: drush_get_url_result
  until: "'OK' in drush_get_url_result.msg"
  retries: 3
  delay: 10
  when: drush_check.stat.exists == false or outdated_drush.stdout != ansible_date
