---
- name: Check if Varnish has been installed
  stat:
    path: /etc/default/varnish
  register: varnish
  ignore_errors: True

# TODO: do we need this?
# - name: Check Varnish version
#   command: "dpkg -l | grep -w varnish | awk '{print $3}' | head -c-5"
#   when: varnish.stat.exists == true

- name: Prepare for Varnish installation 1/3
  #ANSIBLE 2 module apt/dnf = package:
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
  when: varnish.stat.exists == false

- name: Prepare for Varnish installation 2/3
  apt_key:
    url: https://repo.varnish-cache.org/GPG-key.txt
    state: present
  when: varnish.stat.exists == false

- name: Prepare for Varnish installation 3/3
  command: echo "deb https://repo.varnish-cache.org/debian/ jessie varnish-{{ varnish_source }}" >> /etc/apt/sources.list.d/varnish-cache.list
  when: varnish.stat.exists == false

- name: Install Varnish
  #ANSIBLE 2 module apt/dnf = package:
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - varnish
  when: varnish.stat.exists == false

- name: Configure Varnish
  lineinfile:
    dest: /etc/default/varnish
    regexp: "^DAEMON_OPTS=\"-a :6081"
    line: "DAEMON_OPTS=\"-a :80"
  when: varnish.stat.exists == false

- name: Check if the default Varnish VCL exists
  stat:
    path: /etc/default/varnish.vcl
  ignore_errors: True
  register: vcl

- name: Create the default Varnish VCL
  file:
    path: /etc/default/varnish.vcl
    state: touch
    mode: 0644
  when: varnish.stat.exists == false or vcl.stat.exists == false

- name: Configure the Varnish VCL
  blockinfile:
    dest: /etc/default/varnish.vcl
    block: |
      backend default {
          .host = "203.0.113.2";
          .port = "8080";
      }
  notify: Restart Varnish
  when: vcl.stat.exists == false
