---
- hosts: drucker_reverse_proxy
  sudo: yes

  gather_facts: no
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  roles:
    - yaegashi.blockinfile
  tasks:
    - include: common/ssh.yml tags=ssh
    - include: common/system.yml tags=system
    - include: common/varnish.yml tags=varnish
