mysql_creds: root
drupal_creds: admin
mysql_release: 5.5
pma_stable_release: 4.6.0
drush_stable_release: 8.0.5
drupal_dev_release: 8.1.x
webroot: /var/www/html
drucker_install: /var/www/html/drucker
drush_path: /usr/local/bin/drush
composer_path: /usr/local/bin/composer
