---
- name: Clean up system packages
  package:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
  - vim-tiny

- name: Deploy sources.list template with contrib and non-free repositories
  copy:
    src: "{{ sources_list_source_file }}"
    dest: "{{ sources_list }}"
    mode: 0644

- name: Add Debian codename to sources.list template
  replace:
    dest: "{{ sources_list }}"
    regexp: '^(.*)CODENAME(.*)$'
    replace: '\1{{ codename }}\2'

- name: Refresh APT
  apt:
    update_cache: yes

- name: Install system packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  # Useful to run commands as a non-privileged user.
  # E.g. /opt/solr/bin/solr start
  # See https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user
  - acl
  # Needed for Ansible's APT module to perform upgrades.
  # See https://github.com/ansible/ansible/issues/22673
  - aptitude
  - ack-grep
  - apt-transport-https
  - curl
  - dstat
  - exuberant-ctags
  - git
  - htop
  - iputils-ping
  # phantomjs secret dependency
  - libfontconfig1
  - logrotate
  - lsof
  - ncdu
  - netcat
  - net-tools
  - ntp
  - patchutils
  - strace
  - sysstat
  - telnet
  - tcpdump
  - time
  - vim-gtk
  - wget
  # Allows to resize (/usr/bin/resize) the prompt if $COLUMNS and $LINES are
  # suddenly messed up, e.g. in a tmux session.
  - xterm

- name: Ensure NTP is running
  service:
    name: ntp
    state: started
    enabled: yes

- name: Deploy .bash_aliases
  copy:
    src: "{{ bash_aliases_source_file}}"
    dest: "{{ home }}"
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"
  become: yes
  become_user: "{{ user }}"

- name: Deploy .vimrc file
  copy:
    src: "{{ vimrc_source_file }}"
    dest: "{{ home }}"
    mode: 0644
  become: yes
  become_user: "{{ user }}"

- name: Deploy .vim directory
  copy:
    src: "{{ vim_source_dir }}"
    dest: "{{ home }}"
    mode: 0755
  become: yes
  become_user: "{{ user }}"

- name: Add www-data group to drucker account
  user:
    name: "{{ user }}"
    groups: "{{ apache_user}}"
    append: yes
