---
- name: Check if Varnish has been installed
  stat:
    path: "{{ varnish_config }}"
  register: varnish
  ignore_errors: True

- name: Install Varnish
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - varnish
  when: varnish.stat.exists == false

- name: Deploy Varnish template
  copy:
    src: "{{ varnish_conf_source_file }}"
    dest: /etc/default/
    mode: 0644
  when: varnish.stat.exists == false

- name: "Deploy Varnish's default VCL template"
  copy:
    src: "{{ varnish_default_vcl_source_file}}"
    dest: "{{ varnish_default_path }}"
    mode: 0644
  when: varnish.stat.exists == false

- name: Ensure Varnish is started
  service:
    name: varnish
    enabled: yes
    state: started
