---
- name: "TEST: Drupal Console needs to be correctly installed"
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ drupal_console_binary }}"
    # Not required anymore?
    # - "{{ drupal_console_config_file }}"
  register: drupal_console
  failed_when: drupal_console.stat.exists == false

- name: "TEST: Drupal Console package should be present in composer.json"
  shell: grep -o "{{ drupal_console_composer_package_version }}" {{ composer_json_path }} || echo "absent"
  register: drupal_console_composer
  changed_when: drupal_console_composer.stdout == "absent"
  failed_when: drupal_console_composer.stdout == "absent"

- name: "TEST: Drupal Console packages should be up-to-date"
  shell: cd {{ composer_dir_path }} && composer info {{ drupal_console_composer_package }} | grep versions | awk '{print $NF}'
  register: drupal_console_packages
  changed_when: drupal_console_packages.stdout != drupal_console_launcher_stable_release
  failed_when: drupal_console_packages.stdout != drupal_console_launcher_stable_release

- name: "TEST: Drupal Console Launcher should use the latest stable release"
  shell: drupal --version --root={{ drucker_docroot }} | awk '{print $NF}' | head -n1
  register: drupal_console_launcher_version
  changed_when: drupal_console_launcher_version.stdout != drupal_console_launcher_stable_release
  failed_when: drupal_console_launcher_version.stdout != drupal_console_launcher_stable_release
  ignore_errors: true

- name: "TEST: Check if Drupal Console has been configured in .bashrc"
  shell: grep -o "source \"\$HOME/.console/console.rc\" 2>/dev/null" {{ bashrc }} || echo "absent"
  register: drupal_console_bashrc
  changed_when: drupal_console_bashrc == "absent"
  failed_when: drupal_console_bashrc == "absent"

- name: "TEST: Check if Drupal Console can connect to the drucker database"
  shell: drupal database:connect --root={{ drucker_docroot }} | grep -o "{{ user }}" || echo "Cannot connect to the database"
  register: drupal_console_db_connection
  changed_when: drupal_console_db_connection.stdout == "Cannot connect to the database"
  failed_when: drupal_console_db_connection.stdout == "Cannot connect to the database"
