---
- name: "TEST: Drush needs to be correctly installed"
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ drush_binary }}"
    - "{{ drush_aliases_path }}"
    - "{{ drush_dir }}"
  register: drush
  failed_when: drush.stat.exists == false

- name: "TEST: Drush should use the latest stable release"
  shell: drush version | awk '{print $NF}'
  register: drush_version_check
  changed_when: drush_version_check.stdout != drush_composer_package_version
  failed_when: drush_version_check.stdout != drush_composer_package_version

- name: "TEST: The Drush binary should be a symlink"
  stat:
    path: "{{ drush_binary }}"
  register: drush_symlink

- assert:
   that:
     - drush_symlink.stat.islnk

- name: "TEST: Check if Drush can connect to the drucker database"
  shell: drush @{{ user }}.{{ tld }} sql-connect | grep -o "{{ user }}" || echo "Cannot connect to the database"
  register: drush_db_connection
  changed_when: drush_db_connection.stdout == "Cannot connect to the database"
  failed_when: drush_db_connection.stdout == "Cannot connect to the database"
