---
- name: "TEST: Drush needs to be correctly installed"
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ drush_launcher }}"
    - "{{ drush_alias_path }}"
    - "{{ drush_dir }}"
  register: drush
  failed_when: drush.stat.exists == false

- name: "TEST: Drush Launcher should use the latest stable release"
  shell: drush --version | head -n1 | awk '{print $NF}'
  register: drush_launcher_version_check
  changed_when: drush_launcher_version_check.stdout != drush_launcher_version
  failed_when: drush_launcher_version_check.stdout != drush_launcher_version

- name: "TEST: Check if Drush can connect to the drucker database"
  shell: drush --root={{ webroot }}/{{ user }} sql-connect | grep -o "{{ user }}" || echo "Cannot connect to the database"
  register: drush_db_connection
  changed_when: drush_db_connection.stdout == "Cannot connect to the database"
  failed_when: drush_db_connection.stdout == "Cannot connect to the database"
