---
- name: "TEST: Drush needs to be correctly installed"
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ drush_binary }}"
    - "{{ drush_aliases_path }}"
    - "{{ drush_dir }}"
  register: drush
  failed_when: drush.stat.exists == false

- name: "TEST: Drush should use the latest unstable release"
  shell: drush --version | awk '{print $4}' | head -n1
  register: drush_version_check
  changed_when: drush_version_check.stdout != drush_unstable_release
  failed_when: drush_version_check.stdout != drush_unstable_release
  ignore_errors: true

- name: "TEST: The Drush binary should be executable"
  stat:
    path: "{{ drush_binary }}"
  register: executable_drush

- name: "TEST: The Drush binary isn't executable"
  fail:
    msg: "The Drush binary isn't executable"
  when: executable_drush.stat.mode != "0755"

- name: "TEST: Check if Drush can connect to the drucker database"
  shell: drush @{{ user }}.{{ tld }} sql-connect | grep -o "{{ user }}" || echo "Cannot connect to the database"
  register: drush_db_connection
  changed_when: drush_db_connection.stdout == "Cannot connect to the database"
  failed_when: drush_db_connection.stdout == "Cannot connect to the database"
