---
- name: Check if PHP is installed
  stat:
    path: "{{ php_ini }}"
  register: fpm

- name: Add deb.sury.org GPG signature
  apt_key:
    url: "{{ sury_gpg }}"
    state: present
  when: fpm.stat.exists == false

- name: Add deb.sury.org repository
  apt_repository:
    repo: "{{ sury_deb }}"
    state: present
  when: fpm.stat.exists == false

- name: Update APT cache
  apt:
    update_cache: yes
  when: fpm.stat.exists == false

- name: Install PHP core packages
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - php{{ php_version }}-fpm
    - php{{ php_version }}-cli
    # Provides php-apcu which itself provides php7.1-apcu
    - php{{ php_version }}-common
    - php{{ php_version }}-dev
    # Brings FastCGI support via Debian non-free.
    - libapache2-mod-fastcgi
  when: fpm.stat.exists == false

- name: Install PHP extensions
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    # Provides php7.1-imagick
    - php-imagick
    # Provides php7.1-memcached
    - php-memcached
    - php{{ php_version }}-apcu
    - php{{ php_version }}-curl
    - php{{ php_version }}-gd
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-mcrypt
    - php{{ php_version }}-mysql
    - php{{ php_version }}-xmlrpc
    - php{{ php_version }}-xsl
    - php{{ php_version }}-bz2
  when: fpm.stat.exists == false

- name: Deploy fastcgi.conf template
  copy:
    src: "{{ fastcgi_source_file }}"
    dest: "{{ apache_fastcgi_conf }}"
    mode: 0644
  when: fpm.stat.exists == false

- name: Check if php 7 module is enabled
  stat:
    path: "{{ apache_php_mod }}"
  register: php7_module

- name: Disable php 7 module
  apache2_module:
    state: absent
    name: php7
  notify: Restart PHP-FPM
  when: php7_module.stat.exists == true

- include: php_ini.yml

- name: Ensure PHP extensions directory exists
  file:
    path: "{{ php_extensions }}"
    state: directory
  when: fpm.stat.exists == false
