---
- name: Check if PHP 7.2 is installed
  stat:
    path: "{{ php72_ini }}"
  register: php72_fpm

- name: Install PHP 7.2 core packages
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - php{{ php72_version }}-fpm
    - php{{ php72_version }}-cli
    - php{{ php72_version }}-common
    - php{{ php72_version }}-dev
  when: php72_fpm.stat.exists == false

- name: Install PHP 7.2 extensions
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - php{{ php72_version }}-apcu
    - php{{ php72_version }}-curl
    - php{{ php72_version }}-gd
    - php{{ php72_version }}-mbstring
    - php{{ php72_version }}-mysql
    - php{{ php72_version }}-xmlrpc
    - php{{ php72_version }}-xsl
    - php{{ php72_version }}-bz2
    - php{{ php72_version }}-sqlite3
  when: php72_fpm.stat.exists == false

- name: Check if the PHP version file exists
  stat:
    path: "{{ php_version_file }}"
  register: php_version_file_check
  failed_when: php_version_file_check.stat.exists == false

- name: Store PHP version variable
  shell: cat {{ php_version_file }}
  register: php_read_version
  when: php_version_file_check.stat.exists == true

- name: Retrieve existing vHosts
  shell: ls {{ sites_available }}/*.conf | grep -Ev '(000-default|default-ssl.conf)'
  register: apache_vhosts

- name: Update PHP FPM version in vHosts
  replace:
    dest: "{{ item }}"
    regexp: '^(.*)php{{ php_read_version.stdout }}-fpm.sock(.*)$'
    replace: '\1php{{ php72_version }}-fpm.sock\2'
  with_items:
    - "{{ apache_vhosts.stdout_lines }}"

- name: Switch PHP CLI version
  command: update-alternatives --set php /usr/bin/php{{ php72_version }}

- name: Check if PHP FPM is already started
  shell: pgrep -ln php-fpm | awk '{print $NF}' || echo 'stopped'
  register: phpfpm_is_started

- name: Stop current PHP FPM process
  command: /etc/init.d/php{{ php_read_version.stdout }}-fpm stop
  become: yes
  when: phpfpm_is_started.stdout != 'stopped'

- name: Start PHP 7.2 FPM
  command: /etc/init.d/php{{ php72_version }}-fpm start
  become: yes
  when: php72_version != php_read_version.stdout or phpfpm_is_started.stdout == 'stopped'

- name: Ensure PHP 7.2 FPM is started
  shell: pgrep -ln php-fpm | awk '{print $NF}'
  register: php72fpm_is_started
  notify: Restart Apache

- name: Write new PHP version to file
  copy:
    content: "{{ php72_version }}"
    dest: "{{ php_version_file }}"
  when: php72fpm_is_started.changed
