---
- name: "TEST: Varnish needs to be correctly installed"
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ varnish_config }}"
    - "{{ varnish_default_path }}"
    - "{{ varnish_default_vcl }}"
    - "{{ varnish_source_list_path }}"
  register: varnish
  failed_when: varnish.stat.exists == false

- name: "TEST: Check if Varnish package is installed"
  shell: dpkg -l | grep {{ item }}
  with_items:
    - varnish
  register: varnish_packages
  changed_when: varnish_packages == ''

- name: "TEST: Varnish should listen on port 80"
  shell: grep -o "{{ reverse_proxy_port }}" {{ varnish_config }} ||  || echo "wrong port"
  register: varnish_port_check
  changed_when: varnish_port_check.stdout == "wrong port"
  failed_when: varnish_port_check.stdout == "wrong port"

- name: "TEST: Varnish service needs to be started"
  command: service varnish status | grep -o "is running"
  args:
    warn: no
  register: varnish_service
  changed_when: varnish_service.stdout == "is running"
  failed_when: varnish_service.stdout == "is running"
