---
- name: Check if Varnish APT repository exists
  stat:
    path: "{{ varnish_source_list_path }}"
  register: varnish_apt_repo_check
  changed_when: varnish_apt_repo_check.stat.exists == false

- name: Add Varnish APT key
  apt_key:
    url: "{{ varnish_gpg_key }}"
    state: present
  when: varnish_apt_repo_check.stat.exists == false

- name: Add Varnish repository
  apt_repository:
    repo: "{{ varnish_deb }}"
    state: present
  when: varnish_apt_repo_check.stat.exists == false

- name: Check if MySQL APT repository exists
  stat:
    path: "{{ mysql_apt_file }}"
  register: mysql_apt_repo_check
  changed_when: mysql_apt_repo_check.stat.exists == false

- name: Add MySQL GPG key
  apt_key:
    keyserver: pgp.mit.edu
    id: "{{ mysql_gpg_key }}"
    state: present
  when: mysql_apt_repo_check.stat.exists == false

- name: Install MySQL APT repository config tool
  apt:
    deb: "{{ mysql_apt_repo }}"
  when: mysql_apt_repo_check.stat.exists == false
