---
- name: Check if mirror archives directory exists
  stat:
    path: "{{ mirror_archives_dir }}"
  register: mirror_archives_dir_check
  changed_when: mirror_archives_dir_check.stat.exists == false

- name: Create archives directory
  file:
    path: "{{ mirror_archives_dir }}"
    state: directory
  when: mirror_archives_dir_check.stat.exists == false

- name: Check if Apache Solr archive exists
  stat:
    path: "{{ solr_mirror_archive_path }}"
  register: solr_mirror_archive_path_check
  changed_when: solr_mirror_archive_path_check.stat.exists == false

- name: Download latest Apache Solr archive (this can take a while...)
  get_url:
    url: "{{ solr_download_link }}"
    dest: "{{ mirror_archives_dir }}"
    validate_certs: no
  register: solr_get_url_result
  until: "'OK' in solr_get_url_result.msg"
  retries: 3
  delay: 10
  when: solr_mirror_archive_path_check.stat.exists == false
