---
- name: "TEST: Apache needs to be correctly installed"
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ apache_security_conf }}"
    - "{{ apache_actions_mod }}"
    - "{{ apache_rewrite_mod }}"
    - "{{ apache_proxy_http_mod }}"
  register: apache
  failed_when: apache.stat.exists == false

- name: "TEST: The POODLE SSL v3 vulnerability should be fixed"
  shell: grep -o "SSLProtocol all -SSLv2 -SSLv3" {{ apache_ssl_mod }} || echo "absent"
  register: poodle
  changed_when: poodle.stdout == "absent"
  failed_when: poodle.stdout == "absent"

- name: "TEST: apache2 service needs to be started"
  command: service apache2 status | grep -o "is running"
  args:
    warn: no
  register: apache2_service
  changed_when: apache2_service.stdout == "is running"
  failed_when: apache2_service.stdout == "is running"
