---
- name: "TEST: MariaDB and utilities need to be correctly installed"
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ db_config }}"
    - "{{ db_data }}"
    - "{{ db_backup_path }}"
  register: mariadb_check
  failed_when: mariadb_check.stat.exists == false

- name: "TEST: Check if MariaDB and utilities packages are installed"
  shell: dpkg -l | grep {{ item }}
  with_items:
    - mariadb-server
    - mysql-common
    - python-mysqldb
    - memcached
  register: mariadb_packages
  changed_when: mariadb_packages == ''

- name: "TEST: Check if MariaDB innodb_file_per_table setting is configured"
  shell: grep -o "innodb_file_per_table = 1" {{ db_config }} || echo "missing"
  register: mariadb_innodb_setting
  changed_when: mariadb_innodb_setting.stdout == "missing"
  failed_when: mariadb_innodb_setting.stdout == "missing"

- name: "TEST: Check if MariaDB backup cron job exists"
  shell: crontab -l | grep -o "{{ db_backup_path }}" || echo "missing"
  register: mariadb_backup_cron
  changed_when: mariadb_backup_cron.stdout == "missing"
  failed_when: mariadb_backup_cron.stdout == "missing"

- name: "TEST: Check if MariaDB backup cleanup cron job exists"
  shell: crontab -l | grep -o "mmin +180" || echo "missing"
  register: mariadb_cleanup_cron
  changed_when: mariadb_cleanup_cron.stdout == "missing"
  failed_when: mariadb_cleanup_cron.stdout == "missing"

- name: "TEST: Check if MariaDB remote access is configured"
  shell: grep -o "0.0.0.0" {{ db_config }} || echo "denied"
  register: mariadb_remote_access
  changed_when: mariadb_remote_access.stdout == "denied"
  failed_when: mariadb_remote_access.stdout == "denied"

- name: "TEST: MariaDB service needs to be started"
  command: mysqladmin -u {{ db_creds }} -p{{ db_creds }} status
  args:
    warn: no
  register: mariadb_service
  changed_when: "'Uptime' not in mariadb_service.stdout"
  failed_when: "'Uptime' not in mariadb_service.stdout"
