---
- name: Install libmemcached-tools package
  package:
    # Provides memcstat.
    name: libmemcached-tools
    state: present

- include: playbooks/db/phpmyadmin.yml
- include: playbooks/db/adminer.yml
