---
- name: Install libmemcached-tools package
  package:
    # Provides memcstat.
    name: libmemcached-tools
    state: present

- name: Ensure we can manage remote MySQL databases
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-mysqldb
    - mysql-client

- include: playbooks/db/phpmyadmin.yml
- include: playbooks/db/adminer.yml
