---
- name: Install memcached
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - memcached

- name: Check if memcached is started
  command: pgrep memcached
  register: memcached_status
  changed_when: memcached_status.stdout == ""

- name: Start the memcached daemon
  command: memcached -d -u nobody -m 64 -p 11211 127.0.0.1
  when: memcached_status.stdout == ""
