---
- name: Check if adminer is installed
  stat:
    path: "{{ webroot }}/adminer/index.php"
  register: adminer
  ignore_errors: True

- name: Check adminer version
  shell: grep -o "version {{ adminer_stable_release }}" {{ webroot }}/adminer/index.php || echo "update"
  register: adminer_release
  when: adminer.stat.exists == true
  changed_when: adminer_release == "update"

- name: Create adminer directory
  file:
    path: "{{ webroot }}/adminer"
    state: directory
    mode: 0755
  when: adminer.stat.exists == false

- name: Download latest adminer release
  get_url:
    url: https://www.adminer.org/static/download/{{ adminer_stable_release }}/adminer-{{ adminer_stable_release }}-en.php
    dest: "{{ webroot }}/adminer"
    validate_certs: no
  register: adminer_get_url_result
  until: "'OK' in adminer_get_url_result.msg"
  retries: 3
  delay: 10
  when: adminer.stat.exists == false or adminer_release.stdout == "update"

- name: Rename adminer file
  command: mv {{ webroot }}/adminer/adminer-{{ adminer_stable_release }}-en.php {{ webroot }}/adminer/index.php
  when: adminer.stat.exists == false or adminer_release.stdout == "update"

- name: Check if adminer vHost exists
  stat:
    path: "{{ sites_enabled }}/adminer.conf"
  register: adminer_conf
  ignore_errors: True

- name: Deploy default vHost template
  copy:
    src: files/apache-template.conf
    dest: "{{ sites_available }}"
    mode: 0644
  when: adminer_conf.stat.exists == false

- name: Rename default vHost template
  command: mv {{ sites_available }}/apache-template.conf {{ sites_available }}/adminer.conf
  when: adminer_conf.stat.exists == false

- name: Modify adminer vHost
  replace:
    dest: "{{ sites_available }}/adminer.conf"
    regexp: '^(.*)SITENAME(.*)$'
    replace: '\1adminer\2'
  when: adminer_conf.stat.exists == false

- name: Enable adminer vHost
  file:
    src: ../sites-available/adminer.conf
    dest: "{{ sites_enabled }}/adminer.conf"
    state: link
  notify: Reload Apache
  when: adminer_conf.stat.exists == false
