---
- name: Check if Apache is installed
  stat:
    path: /etc/apache2/conf-available/security.conf
  register: apache
  ignore_errors: True

- name: Install Apache packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - apache2-utils
  when: apache.stat.exists == false

- name: Enable mod_rewrite and proxy_http
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - rewrite
    - proxy_http
  when: apache.stat.exists == false

- name: "Fix the POODLE SSL v3 vulnerability"
  lineinfile:
    dest: "/etc/apache2/mods-available/ssl.conf"
    regexp: "SSLProtocol all"
    line: "\tSSLProtocol all -SSLv2 -SSLv3"
  when: apache.stat.exists == false

- name: Make Apache listen on port 8080
  replace:
    dest: /etc/apache2/ports.conf
    regexp: '^(.*)Listen 80(.*)$'
    replace: 'Listen {{ backend_port }}'
  notify: Restart Apache
  when: apache.stat.exists == false

- name: Support file upload progress through APC
  lineinfile:
    dest: /etc/php5/apache2/php.ini
    line: "apc.rfc1867 = 1"
  when: apache.stat.exists == true

- name: Ensure Apache is started
  service:
    name: apache2
    enabled: yes
    state: started
