---
- name: Check if Code Sniffer phpcs is installed
  stat:
    path: "{{ user_programs_path }}/phpcs"
  register: phpcs

- name: Check if Code Sniffer phpcbf is installed
  stat:
    path: "{{ user_programs_path }}/phpcbf"
  register: phpcbf

- name: Check phpcs version
  shell: phpcs --version | awk '{print $3}'
  register: phpcs_version
  when: phpcs.stat.exists == true
  changed_when: phpcs_version.stdout != "{{ phpcs_stable_release }}"

- name: Check phpcbf version
  shell: phpcbf --version | awk '{print $3}'
  register: phpcbf_version
  when: phpcbf.stat.exists == true
  changed_when: phpcbf_version.stdout != "{{ phpcbf_stable_release }}"

- name: Download phpcs PHAR file
  get_url:
    url: https://github.com/squizlabs/PHP_CodeSniffer/releases/download/{{ phpcs_stable_release }}/phpcs.phar
    dest: /tmp
    mode: 0755
    validate_certs: no
  register: codesniffer_get_url_result
  until: "'OK' in codesniffer_get_url_result.msg"
  retries: 3
  delay: 10
  when: phpcs.stat.exists == false or phpcs_version.stdout != "{{ phpcs_stable_release }}"

- name: Rename phpcs PHAR file
  command: mv /tmp/phpcs.phar /tmp/phpcs
  when: phpcs.stat.exists == false or phpcs_version.stdout != "{{ phpcs_stable_release }}"

- name: Install phpcs globally
  command: mv /tmp/phpcs {{ user_programs_path }}/
  when: phpcs.stat.exists == false or phpcs_version.stdout != "{{ phpcs_stable_release }}"

- name: Download phpcbf PHAR file
  get_url:
    url: https://github.com/squizlabs/PHP_CodeSniffer/releases/download/{{ phpcbf_stable_release }}/phpcbf.phar
    dest: /tmp
    mode: 0755
    validate_certs: no
  when: phpcbf.stat.exists == false or phpcbf_version.stdout != "{{ phpcbf_stable_release }}"

- name: Rename phpcbf PHAR file
  command: mv /tmp/phpcbf.phar /tmp/phpcbf
  when: phpcbf.stat.exists == false or phpcbf_version.stdout != "{{ phpcbf_stable_release }}"

- name: Install phpcbf globally
  command: mv /tmp/phpcbf {{ user_programs_path }}/
  when: phpcbf.stat.exists == false or phpcbf_version.stdout != "{{ phpcbf_stable_release }}"
