---
- name: Check if Coder is installed
  stat:
    path: /home/{{ user }}/.composer/vendor/drupal/coder
  register: coder

- name: Install Coder
  composer:
    command: require
    arguments: drupal/coder {{ coder_stable_release }}
    working_dir: /home/{{ user }}/.composer
  when: coder.stat.exists == false

- name: Check if Coder is up-to-date
  composer:
    command: info
    arguments: drupal/coder
    working_dir: /home/{{ user }}/.composer
  register: coder_stable_release_check
  when: coder.stat.exists == true
  changed_when: '"{{ coder_stable_release }}" not in coder_stable_release_check.stdout'

- name: Update Coder
  composer:
    command: require
    arguments: drupal/coder {{ coder_stable_release }}
    working_dir: /home/{{ user }}/.composer
  when: coder.stat.exists == true and "{{ coder_stable_release }}" not in coder_stable_release_check.stdout

- name: Ensure .composer directory has correct permissions
  file:
    path: /home/{{ user }}/.composer
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: yes

- name: Check if Coder bash aliases exist
  shell: egrep -o 'MANAGED CODE SNIFFER BLOCK' /home/{{ user }}/.bashrc || echo "absent"
  register: coder_aliases
  changed_when: coder_aliases == "absent"

- name: Add Code Sniffer aliases
  blockinfile:
    dest: /home/{{ user }}/.bashrc
    block: |
      alias drupalcs="phpcs --standard=Drupal --extensions={{ codesniffer_extensions }}"
      alias drupalpractice="phpcs --standard=DrupalPractice --extensions={{ codesniffer_extensions }}"
      alias drupalfix="phpcbf --standard=Drupal --extensions={{ codesniffer_extensions }}"
    insertafter: EOF
    marker: "# {mark} MANAGED CODE SNIFFER BLOCK"
  when: coder_aliases.stdout == 'absent'

- name: Register Drupal and DrupalPractice with PHPCS
  command: phpcs --config-set installed_paths /home/{{ user }}/.composer/vendor/drupal/coder/coder_sniffer
  when: coder.stat.exists == false
