---
- name: Check if Code Sniffer is installed
  stat:
    path: "{{ user_programs_path }}/phpcs"
  register: codesniffer

- name: Download Code Sniffer phpcs PHAR file
  get_url:
    url: https://github.com/squizlabs/PHP_CodeSniffer/releases/download/{{ codesniffer_stable_release }}/phpcs.phar
    dest: /tmp
    mode: 0755
  when: codesniffer.stat.exists == false

- name: Rename Code Sniffer phpcs PHAR file
  command: mv /tmp/phpcs.phar /tmp/phpcs
  when: codesniffer.stat.exists == false

- name: Move phpcs to PHP directory
  command: mv /tmp/phpcs {{ user_programs_path }}/
  when: codesniffer.stat.exists == false

- name: Download Code Sniffer phpcbf
  get_url:
    url: https://github.com/squizlabs/PHP_CodeSniffer/releases/download/{{ codesniffer_stable_release }}/phpcbf.phar
    dest: /tmp
    mode: 0755
  when: codesniffer.stat.exists == false

- name: Rename Code Sniffer phpcbf PHAR file
  command: mv /tmp/phpcbf.phar /tmp/phpcbf
  when: codesniffer.stat.exists == false

- name: Move phpcbf to PHP directory
  command: mv /tmp/phpcbf {{ user_programs_path }}/
  when: codesniffer.stat.exists == false
