---
- name: Check if MySQL dump exists
  stat:
    path: /tmp/{{ sitename }}.sql.gz
  register: dump
  ignore_errors: True

- name: Copy MySQL dump
  copy:
    src: "{{ item }}"
    dest: /tmp/{{ sitename }}.sql.gz
    mode: 0644
  with_fileglob:
    - import/*.sql.gz
  when: dump.stat.exists == false

- name: Check if new database exists (or create it)
  mysql_db:
    login_user: "{{ mysql_creds }}"
    login_password: "{{ mysql_creds }}"
    login_host: "{{ db_ip }}"
    login_port: "{{ mysql_port }}"
    config_file: "{{ my_cnf }}"
    name: "{{ sitename }}"
    state: present
  when: dump.stat.exists == false

- name: Restore MySQL dump
  mysql_db:
    login_user: "{{ mysql_creds }}"
    login_password: "{{ mysql_creds }}"
    login_host: "{{ db_ip }}"
    login_port: "{{ mysql_port }}"
    config_file: "{{ my_cnf }}"
    name: "{{ sitename }}"
    state: import
    target: /tmp/{{ sitename }}.sql.gz
  when: dump.stat.exists == false

- name: Delete database dump
  file:
    path: /tmp/{{ sitename }}.sql.gz
    state: absent
  when: dump.stat.exists == false
