---
- name: Check if repo directory exists
  stat:
    path: "{{ git_repo_directory }}"
  register: git_repo_dir
  ignore_errors: True

- name: Create repo directory
  file:
    path: "{{ git_repo_directory }}"
    state: directory
  become: yes
  become_user: "{{ user }}"
  when: git_repo_dir.stat.exists == false

- name: Check if Drupal clone exists
  stat:
    path: "{{ drupal_git_clone_path }}"
  register: git_clone_dir
  ignore_errors: True

- name: Clone Drupal repository (this can take a while...)
  git:
    repo: "{{ drupal_git_clone_url }}"
    dest: "{{ drupal_git_clone_path }}"
    version: 8.3.x
  become: yes
  become_user: "{{ user }}"
  when: git_clone_dir.stat.exists == false
