---
- name: "DELETE: Delete database"
  mysql_db:
    login_user: "{{ mysql_creds }}"
    login_password: "{{ mysql_creds }}"
    login_host: "{{ db_ip }}"
    login_port: "{{ mysql_port }}"
    config_file: "{{ my_cnf }}"
    name: "{{ sitename }}"
    state: absent

- name: "DELETE: Check if docroot exists"
  stat:
    path: "{{ webroot }}/{{ sitename }}"
  register: docroot_check
  ignore_errors: True

- name: "DELETE: Delete docroot"
  file:
    path: "{{ webroot }}/{{ sitename }}"
    state: absent
  when: docroot_check.stat.exists == true and "{{ sitename }}" != 'import'

- name: "DELETE: Check if vHost exists"
  stat:
    path: "{{ sites_enabled }}/{{ sitename }}.conf"
  register: apache_conf
  ignore_errors: True

- name: "DELETE: Delete vHost"
  file:
    path: "{{ sites_enabled }}/{{ sitename }}.conf"
    state: absent
  when: apache_conf.stat.exists == true

- name: "DELETE: Check if Drush aliases exist"
  stat:
    path: "{{ drush_aliases_path }}/{{ sitename }}.aliases.drushrc.php"
  register: sitename_aliases

- name: "DELETE: Delete Drush aliases"
  file:
    path: "{{ drush_aliases_path }}/{{ sitename }}.aliases.drushrc.php"
    state: absent
  when: sitename_aliases.stat.exists == true
