---
- name: "REINSTALL: Check if latest Drupal dev archive exists"
  stat:
    path: /tmp/drupal-{{ drupal_dev_release }}-dev.tar.gz
  register: drupal_archive
  ignore_errors: True

- name: "REINSTALL: Check if Drupal archive is outdated"
  shell: date -r /tmp/drupal-{{ drupal_dev_release }}-dev.tar.gz +%F
  register: outdated_drupal

- name: "REINSTALL: Delete Drupal archive"
  file:
    path: /tmp/drupal-{{ drupal_dev_release }}-dev.tar.gz
    state: absent
  when: drupal_archive.stat.exists == true and outdated_drupal.stdout != "{{ ansible_date_time.date }}"

- name: "REINSTALL: Check if drucker docroot exists"
  stat:
    path: "{{ docroot }}"
  register: drucker_docroot
  ignore_errors: True

- name: "REINSTALL: Deletes drucker docroot"
  file:
    path: "{{ docroot }}"
    state: absent
  when: drucker_docroot.stat.exists == true

- include: playbooks/drupal.yml
