---
# Drupal Console Launcher
- name: Check if Drupal Console Launcher is installed
  stat:
    path: "{{ drupal_console_binary }}"
  register: drupal_console

- name: Check Drupal Console Launcher version
  shell: drupal --version | awk '{print $NF}' | head -n1
  register: drupal_console_launcher_check
  when: drupal_console.stat.exists == true
  changed_when: drupal_console_launcher_check.stdout != "{{ drupal_console_launcher_stable_release }}"

- name: Install Drupal Console launcher
  get_url:
    url: "{{ drupal_console_launcher_download_link }}"
    dest: "{{ drupal_console_binary }}"
    mode: 0755
    validate_certs: no
  register: console_get_url_result
  until: "'OK' in console_get_url_result.msg"
  retries: 3
  delay: 10
  when: drupal_console.stat.exists == false

- name: Update Drupal Console Launcher
  command: drupal self-update
  when: drupal_console.stat.exists == true and drupal_console_launcher_check.stdout != "{{ drupal_console_launcher_stable_release }}"

# Drupal Console Composer package
- name: Check Drupal Console version in composer.json file
  shell: grep -E "\"{{ drupal_console_composer_package }}*.*" {{ composer_json_path }} | awk '{print $NF}' | tr -d '",'
  register: drupal_console_composer_package_version_check
  changed_when: drupal_console_composer_package_version_check.stdout != "{{ drupal_console_composer_package_version }}"

- name: Install Drupal Console Composer package via composer.json
  composer:
    command: require
    arguments: "{{ drupal_console_composer_package }}:{{ drupal_console_composer_package_version }} --prefer-dist --optimize-autoloader"
    working_dir: "{{ composer_dir_path }}"
  become: yes
  become_user: "{{ user }}"
  when: drupal_console_composer_package_version_check.stdout != "{{ drupal_console_composer_package_version }}"

- name: Update Drupal Console Composer package
  composer:
    command: update
    arguments: "{{ drupal_console_composer_package }} --with-dependencies"
    working_dir: "{{ composer_dir_path }}"
  become: yes
  become_user: "{{ user }}"
  when: drupal_console_composer_package_version_check.stdout != "{{ drupal_console_composer_package_version }}"

- name: Initialize Drupal Console
  command: drupal init --override --no-interaction
  #when: drupal_console.stat.exists == false or drupal_console_stable_release_check.stdout != "{{ drupal_console_composer_package_version }}"
  become: yes
  become_user: "{{ user }}"

- name: Check if Drupal Console has been configured in .bashrc
  shell: grep -o "source \"\$HOME/.console/console.rc\" 2>/dev/null" {{ bashrc }} || echo "absent"
  register: drupal_console_bashrc
  changed_when: drupal_console_bashrc == "absent"

- name: Configure Drupal Console in .bashrc
  lineinfile:
    dest: "{{ bashrc }}"
    line: "source \"$HOME/.console/console.rc\" 2>/dev/null"
    insertafter: EOF
  when: drupal_console_bashrc.stdout == 'absent'
