---
- name: Check if Drupal Console is installed
  stat:
    path: "{{ user_programs_path }}/drupal"
  register: drupal_console

- name: Check Drupal Console version
  shell: drupal --version | awk '{print $4}'
  register: drupal_console_stable_release_check
  when: drupal_console.stat.exists == true

- name: Install Drupal Console globally
  get_url:
    url: https://drupalconsole.com/installer
    dest: "{{ user_programs_path }}/drupal"
    mode: 0755
    validate_certs: no
  when: drupal_console.stat.exists == false

- name: Update Drupal Console
  command: drupal self-update
  when: drupal_console.stat.exists == true and drupal_console_stable_release_check.stdout != "{{ drupal_console_stable_release }}"

- name: Initialize Drupal Console
  command: drupal init --override
  when: drupal_console.stat.exists == false

- name: Check if Drupal Console has been configured in .bashrc
  shell: grep -o "source \"\$HOME/.console/console.rc\" 2>/dev/null" /home/{{ user }}.bashrc || echo "absent"
  register: drupal_console_bashrc

- name: Configure Drupal Console in .bashrc
  lineinfile:
    dest: /home/{{ user }}/.bashrc
    line: "source \"$HOME/.console/console.rc\" 2>/dev/null"
    insertafter: EOF
  when: drupal_console_bashrc.stdout == 'absent'
