---
- name: "Check if Drupal checkout branch is current"
  shell: cd {{ drupal_git_clone_path }} && git branch -l | grep "* {{ drupal_head }}" || echo "wrong branch"
  register: drupal_branch_check

- name: "Switch Drupal checkout to current branch"
  shell: cd {{ drupal_git_clone_path }} && git checkout {{ drupal_head }}
  when: drupal_branch_check.stdout == "wrong branch"

- name: "Check if Drupal checkout can be updated"
  shell: cd {{ drupal_git_clone_path }} && git pull
  become: yes
  become_user: "{{ user }}"
