---
- include: playbooks/drupal-clone.yml

- name: Check if drucker docroot exists
  stat:
    path: "{{ docroot }}"
  register: drucker
  ignore_errors: True

- name: Create drucker docroot
  command: cp -R {{ drupal_git_clone_path }} {{ docroot }}
  become: yes
  become_user: "{{ user }}"
  when: drucker.stat.exists == false

- name: Ensure we can manage remote MySQL databases
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-mysqldb

- name: Check if drucker database exists
  stat:
    path: "{{ mysql_data }}/{{ user }}"
  register: drucker_db

- name: Delete files directory when reinstalling
  file:
    path: "{{ files_dir }}"
    state: absent
  when: drucker_db.stat.exists == false

- name: Make sure default site has correct permissions
  file:
    path: "{{ docroot }}/{{default_site}}"
    mode: 0755
  when: drucker_db.stat.exists == false

- name: Create files directory
  file:
    path: "{{ files_dir }}"
    state: directory
    mode: 0777
  become: yes
  become_user: "{{ user }}"
  when: drucker.stat.exists == false or drucker_db.stat.exists == false

- name: Create libraries directory
  file:
    path: "{{ libraries_dir }}"
    state: directory
  become: yes
  become_user: "{{ user }}"
  when: drucker.stat.exists == false or drucker_db.stat.exists == false

- name: Create simpletest directory
  file:
    path: "{{ simpletest_dir }}"
    state: directory
    mode: 0777
  become: yes
  become_user: "{{ user }}"
  when: drucker.stat.exists == false

- name: Delete settings.php file when reinstalling
  file:
    path: "{{ settings_php }}"
    state: absent
  when: drucker_db.stat.exists == false

- name: Create settings.php file
  command: cp {{ default_settings_php }} {{ settings_php }}
  become: yes
  become_user: "{{ user }}"
  when: drucker.stat.exists == false or drucker_db.stat.exists == false

- name: Create services.yml file
  command: cp {{ default_services_yml }} {{ services_yml }}
  become: yes
  become_user: "{{ user }}"
  when: drucker.stat.exists == false or drucker_db.stat.exists == false

- name: Add trusted_host_patterns in settings.php
  blockinfile:
    dest: "{{ settings_php }}"
    block: |
      $settings['trusted_host_patterns'] = array(
        '^{{ user }}\.{{ tld }}$',
      );
  when: drucker.stat.exists == false or drucker_db.stat.exists == false

- name: Prepare settings.php for memcached support
  blockinfile:
    dest: "{{ settings_php }}"
    block: |
      /**
       * drucker comes with memcached pre-configured. You simply need to install the
       * memcache module and add the below lines to enable memcache support.
       * DO NOT uncomment this block as it's managed by Ansible.
       * $settings['cache']['default'] = 'cache.backend.memcache';
       * $settings['memcache']['servers'] = ['{{ db_ip }}:11211' => 'default'];
       */
  when: drucker.stat.exists == false or drucker_db.stat.exists == false

- name: Ensure drucker database is wiped before installing
  mysql_db:
    login_user: "{{ mysql_creds }}"
    login_password: "{{ mysql_creds }}"
    login_host: "{{ db_ip }}"
    login_port: "{{ mysql_port }}"
    name: "{{ user }}"
    config_file: "{{ my_cnf }}"
    state: absent
  when: drucker.stat.exists == false

- name: Create drucker database
  mysql_db:
    login_user: "{{ mysql_creds }}"
    login_password: "{{ mysql_creds }}"
    login_host: "{{ db_ip }}"
    login_port: "{{ mysql_port }}"
    name: "{{ user }}"
    config_file: "{{ my_cnf }}"
    state: present
  when: drucker.stat.exists == false or drucker_db.stat.exists == false

- name: Check if drucker vHost exists
  stat:
    path: "{{ drucker_vhost }}"
  register: drucker_vhost_check
  ignore_errors: True

- name: Delete default vHost
  file:
    path: "{{ default_vhost }}"
    state: absent
  when: drucker_vhost_check.stat.exists == false

- name: Delete default vHost symlink
  file:
    path: "{{ default_vhost }}"
    state: absent
  when: drucker_vhost_check.stat.exists == false

- name: Deploy default vHost template
  copy:
    src: "{{ apache_template_source_file }}"
    dest: "{{ sites_available }}"
    mode: 0644
  when: drucker_vhost_check.stat.exists == false

- name: Rename default vHost template
  command: mv {{ vhost_template }} {{ drucker_available_vhost }}
  when: drucker_vhost_check.stat.exists == false

- name: Modify drucker vHost
  replace:
    dest: "{{ drucker_available_vhost }}"
    regexp: '^(.*)SITENAME(.*)$'
    replace: '\1{{ user }}\2'
  when: drucker_vhost_check.stat.exists == false

- name: Enable drucker vHost
  file:
    src: ../sites-available/{{ user }}.conf
    dest: "{{ drucker_vhost }}"
    state: link
    force: yes
  register: test
  notify: Reload Apache
  when: drucker_vhost_check.stat.exists == false

- name: Check if drucker Drush aliases exist
  stat:
    path: "{{ drucker_aliases }}"
  register: drucker_aliases

- name: Create site-aliases directory
  file:
    path: "{{ drush_aliases_path }}"
    state: directory
  when: drucker_aliases.stat.exists == false

- name: Deploy drucker Drush aliases
  copy:
    src: "{{ drush_aliases_source_file }}"
    dest: "{{ drush_aliases_path }}"
    mode: 0644
  when: drucker_aliases.stat.exists == false
  ignore_errors: true

- name: Rename default Drush aliases
  command: mv {{ drush_aliases_filepath }} {{ drush_aliases_path }}/{{ user }}.aliases.drushrc.php
  when: drucker_aliases.stat.exists == false

- name: Modify Drush aliases
  replace:
    dest: "{{ drush_aliases_path }}/{{ user }}.aliases.drushrc.php"
    regexp: '^(.*)SITENAME(.*)$'
    replace: '\1{{ user }}\2'
  when: drucker_aliases.stat.exists == false

- name: Create .drush directory
  file:
    path: "{{ drush_dir }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ user }}"
  when: drucker_aliases.stat.exists == false

- name: Pull vendor dependencies
  composer:
    command: install
    working_dir: "{{ docroot }}"
  become: yes
  become_user: "{{ user }}"
  when: drucker.stat.exists == false

- name: Install Drupal
  command: drush @{{ user }}.{{ tld }} site-install standard install_configure_form.update_status_module='array(FALSE,FALSE)' -qy --db-url=mysql://{{ mysql_creds }}:{{ mysql_creds }}@{{ db_ip }}:{{ mysql_port }}/{{ user }} --site-name={{ user }} --site-mail={{ drupal_creds }}@{{ user }}.{{ tld }} --account-name={{ drupal_creds }} --account-pass={{ drupal_creds }} --account-mail={{ drupal_creds }}@{{ user }}.{{ tld }}
  become: yes
  become_user: "{{ user }}"
  when: drucker.stat.exists == false or drucker_db.stat.exists == false

- name: Retrieve path to sync directory
  shell: drush @{{ user }}.{{ tld }} st | grep Sync | awk '{print $NF}'
  register: sync_dir
  when: drucker.stat.exists == false or drucker_db.stat.exists == false

- name: Make sure the sync directory is writable
  file:
    path: "{{ docroot }}/{{ sync_dir.stdout }}"
    mode: 0777
  when: drucker.stat.exists == false or drucker_db.stat.exists == false

- name: Check if phpunit.xml file exists
  stat:
    path: "{{ phpunit_xml }}"
  register: phpunit

- name: Deploy phpunit.xml file
  copy:
    src: "{{ phpunit_source_file }}"
    dest: "{{ docroot }}/core/"
    mode: 0644
  become: yes
  become_user: "{{ user }}"
  when: phpunit.stat.exists == false

- name: Modify phpunit.xml file
  replace:
    dest: "{{ phpunit_xml }}"
    regexp: '^(.*)SITENAME(.*)$'
    replace: '\1{{ user }}\2'
  when: phpunit.stat.exists == false

- name: Check if import directories exist
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ import_dir }}"
    - "{{ archives_dir }}"
  register: import_directories
  ignore_errors: True

- name: Create import directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ apache_user }}"
  with_items:
    - "{{ import_dir }}"
    - "{{ archives_dir }}"
  when: import_directories.results[0]['item'] or import_directories.results[1]['item']

- name: Check if .gitignore exists
  stat:
    path: "{{ drupal_gitignore }}"
  register: gitignore
  ignore_errors: True

- name: Create .gitignore file
  copy:
    src: "{{ gitignore_source_file }}"
    dest: "{{ docroot }}"
    mode: 0644
  become: yes
  become_user: "{{ user }}"
  when: gitignore.stat.exists == false

- name: Add all new files under version control
  shell: git -C {{ docroot }} add . && git -C {{ docroot }} commit -m "Initial drucker commit"
  become: yes
  become_user: "{{ user }}"
  when: drucker.stat.exists == false

- name: Check if all hostnames are configured
  shell: grep -E '({{ phpmyadmin_hostname }}.{{ tld }}|{{ adminer_hostname }}.{{ tld }})' {{ hosts_file }} || echo "absent"
  register: additional_hostnames
  changed_when: additional_hostnames.stdout == "absent"

- name: Make sure the web container can reach all hostnames
  shell: echo "{{ web_ip }}    {{ item }}.{{ tld }}" >> {{ hosts_file }}
  with_items:
  - "{{ phpmyadmin_hostname }}"
  - "{{ adminer_hostname }}"
  when: additional_hostnames.stdout == "absent"

- name: Check if Solr hostname is configured
  shell: grep -o "{{ search_ip }}" {{ hosts_file }} || echo "absent"
  register: search_hostname
  changed_when: search_hostname.stdout == "absent"

- name: Make sure Drupal can talk to the Solr backend
  shell: echo "{{ search_ip }}    search.{{ tld }}" >> {{ hosts_file }}
  when: search_hostname.stdout == "absent"
