---
- name: Check if Drush is installed
  stat:
    path: "{{ drush_binary }}"
  register: drush

- name: Check Drush version
  shell: drush --version | awk '{print $4}' | head -n1
  register: drush_stable_release_check
  when: drush.stat.exists == true
  changed_when: drush_stable_release_check.stdout != "{{ drush_stable_release }}"

- name: Install Drush globally
  get_url:
    url: "{{ drush_download_link }}"
    dest: "{{ drush_binary }}"
    force: yes
    mode: 0755
    validate_certs: no
  register: drush_get_url_result
  until: "'OK' in drush_get_url_result.msg"
  retries: 3
  delay: 10
  when: drush.stat.exists == false or drush_stable_release_check.stdout != "{{ drush_stable_release }}"
