---
- name: Check if web container is part of the trusted pool
  shell: gluster peer status
  register: web_peer
  when: inventory_hostname == "{{ web2_ip }}"

- name: Add web container to trusted pool
  command: gluster peer probe "{{ backend_ip }}"
  register: web_peer_status
  when: inventory_hostname == "{{ web2_ip }}"

- name: Check if Gluster volume already exists
  stat:
    path: /var/lib/glusterd/vols/gv0
  register: gluster_volume_check

- name: Create Gluster volume
  command: gluster volume create gv0 replica 2 "{{ backend_ip }}":"{{ brick }}" "{{ web2_ip }}":"{{ brick }}"
  register: create_gv0
  when: gluster_volume_check.stat.exists == false

- name: Check if Gluster volume has already been started
  shell: grep status /var/lib/glusterd/vols/gv0/info | tail -c 2
  register: gluster_volume_is_started

- name: Start Gluster volume
  command: gluster volume start gv0
  when: (gluster_volume_is_started.stdout != "1") and (inventory_hostname == "{{ web2_ip }}")

- name: Create mount point for brick
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ web2_ip }}:/gv0"
    fstype: glusterfs
    state: mounted

- name: Check if files dir exists under the brick
  stat:
    path: "{{ brick }}/files"
  register: files_brick

- name: Move files dir to the brick
  command: mv "{{ drucker_install }}/sites/default/files" "{{ brick }}/"
  when: (files_brick.stat.exists == false) and (inventory_hostname != "{{ web2_ip }}")

- name: Create Drucker GFS symlink
  file:
    src: "{{ gluster_mount_dir }}/files"
    dest: "{{ drucker_install }}/sites/default/files"
    state: link
  when: (files_brick.stat.exists == true) and (inventory_hostname != "{{ web2_ip }}")
