---
- name: Check if GlusterFS has been installed
  stat:
    path: "{{ gluster_vol_path }}"
  register: gluster
  ignore_errors: True

- name: Prepare for GlusterFS installation 1/2
  apt_key:
    url: "{{ gluster_pub_key }}"
    state: present
  when: gluster.stat.exists == false

- name: Prepare for GlusterFS installation 2/2
  apt_repository:
    repo: "{{ gluster_deb }}"
    state: present
  when: gluster.stat.exists == false

- name: Install GlusterFS
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - glusterfs-server
    - glusterfs-client
  when: gluster.stat.exists == false

- name: Create GlusterFS brick
  file:
    path: "{{ brick }}"
    state: directory
    mode: 0777

- name: Create mount point
  file:
    path: "{{ gluster_mount_dir }}"
    state: directory
    mode: 0777

- name: Ensure GlusterFS is started
  service:
    name: glusterfs-server
    enabled: yes
    state: started
