---
- name: Check if GlusterFS has been installed
  stat:
    path: /etc/glusterfs/glusterd.vol
  register: gluster
  ignore_errors: True

- name: Prepare for GlusterFS installation 1/2
  apt_key:
    url: http://download.gluster.org/pub/gluster/glusterfs/LATEST/rsa.pub
    state: present
  when: gluster.stat.exists == false

- name: Prepare for GlusterFS installation 2/2
  apt_repository:
    repo: 'deb http://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/{{ codename }}/apt {{ codename }} main'
    state: present
  when: gluster.stat.exists == false

- name: Install GlusterFS
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - glusterfs-server
    - glusterfs-client
  when: gluster.stat.exists == false

- name: Ensure GlusterFS is started
  service:
    name: glusterfs-server
    enabled: yes
    state: started
