---
- name: Check if web container is part of the trusted pool
  shell: gluster peer status
  register: web_peer
  when: inventory_hostname == "{{ gluster_ip }}"

- name: Add web container to trusted pool
  command: gluster peer probe "{{ backend_ip }}"
  register: web_peer_status
  when: inventory_hostname == "{{ gluster_ip }}"

- name: Check if Gluster volume already exists
  command: gluster volume info
  register: gluster_volume_check
  when: inventory_hostname == "{{ gluster_ip }}"

- name: Create Gluster volume
  command: gluster volume create gv0 replica 2 "{{ backend_ip }}":"{{ brick }}" "{{ gluster_ip }}":"{{ brick }}"
  register: create_gv0
  when: ("'No volumes present' in gluster_volume_check.stderr" or "'Volume gv0 already exists' not in gluster_volume_check.stderr") and (inventory_hostname == "{{ gluster_ip }}")

- name: Check if Gluster volume has already been started
  shell: gluster volume info gv0 | grep Started | awk '{print $NF}'
  register: gluster_volume_is_started
  when: inventory_hostname == "{{ gluster_ip }}"

- name: Start Gluster volume
  command: gluster volume start gv0
  when: ("'Started' not in gluster_volume_is_started.stdout") and (inventory_hostname == "{{ gluster_ip }}")

- name: Create mount point for brick
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ gluster_ip }}:/gv0"
    fstype: glusterfs
    state: mounted
