---
- name: Install APT cache mirror
  package:
    name: apt-cacher-ng
    state: installed
    force: yes

- name: Check if the APT mirror is configured to allow remote access
  shell: grep -o "BindAddress:\ 0.0.0.0" {{ mirror_config }} || echo "denied"
  register: mirror_remote_access
  changed_when: mirror_remote_access.stdout == "denied"

- name: Configure the APT mirror to allow remote access
  lineinfile:
    dest: "{{ mirror_config }}"
    line: "BindAddress: 0.0.0.0"
    insertafter: EOF
  when: mirror_remote_access.stdout == "denied"

- name: Check if the APT mirror is configured to run as a service
  shell: grep -o "# PidFile" {{ mirror_config }} || echo "configured"
  register: mirror_service
  changed_when: mirror_service.stdout != "configured"

- name: Enable the APT mirror to run as a service
  lineinfile:
    dest: "{{ mirror_config }}"
    regexp: "# PidFile: /var/run/apt-cacher-ng/pid"
    line: "PidFile: /var/run/apt-cacher-ng/pid"
  when: mirror_service.stdout != "configured"

- name: Check if the APT mirror is configured to run as a service
  shell: grep -E "^PassThroughPattern:\ .*" {{ mirror_config }} || echo "not configured"
  register: passthrough
  changed_when: passthrough.stdout == "not configured"

- name: Enable SSL/TLS support
  lineinfile:
    dest: "{{ mirror_config }}"
    line: "PassThroughPattern: .*"
    insertafter: "^# PassThroughPattern: .* # this would allow CONNECT to everything"
  when: passthrough.stdout == "not configured"

- name: Restart APT mirror service
  service:
    name: apt-cacher-ng
    enabled: yes
    state: restarted

- name: Update APT cache
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600
  register: update_cache

- name: Ensure Apache is started
  service:
    name: apache2
    enabled: yes
    state: started
