---
- name: Install MySQL utilities
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mytop

- name: Grant MySQL access to remote web node
  shell: >
    mysql -u {{ mysql_creds }} -p{{ mysql_creds }} -NBe
    'GRANT ALL PRIVILEGES ON *.* TO "{{ mysql_creds }}"@"{{ web_ip }}" IDENTIFIED BY "{{ mysql_creds }}";'

- name: Restart MySQL
  service:
    name: mysql
    enabled: yes
    state: restarted
