---
- name: Check if nginx is installed
  stat:
    path: /etc/nginx/nginx.conf
  register: nginx
  ignore_errors: True

- name: Install nginx
  #ANSIBLE 2 module apt/dnf = package:
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
  when: nginx.stat.exists == false

- name: Check if default nginx site exists
  stat:
    path: /etc/nginx/sites-enabled/default
  register: nginx_default
  ignore_errors: True

- name: Delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: nginx_default.stat.exists == true

- name: Check if nginx drucker host exists
  stat:
    path: /etc/nginx/conf.d/{{ user }}.conf
  register: nginx_drucker_host
  ignore_errors: True

- name: Deploy nginx template
  copy:
    src: files/nginx-template.conf
    dest: /etc/nginx/conf.d/
    mode: 0644
  when: nginx_drucker_host.stat.exists == false

- name: Rename nginx template
  command: mv /etc/nginx/conf.d/nginx-template.conf /etc/nginx/conf.d/{{ user }}.conf
  when: nginx_drucker_host.stat.exists == false

- name: Modify default nginx port
  replace:
    dest: /etc/nginx/conf.d/{{ user }}.conf
    regexp: '^(.*)listen localhost:80;(.*)$'
    replace: '\1listen localhost:{{ backend_port }};\2'
  when: nginx_drucker_host.stat.exists == false

- name: Modify nginx proxy_pass
  replace:
    dest: /etc/nginx/conf.d/{{ user }}.conf
    regexp: '^(.*)proxy_pass http://0.0.0.0:{{ reverse_proxy_port }};(.*)$'
    replace: '\1proxy_pass http://{{ backend_ip }}:{{ backend_port }};\2'
  when: nginx_drucker_host.stat.exists == false

- name: Ensure nginx is started
  service:
    name: nginx
    enabled: yes
    state: started
