---
- name: Check if PHP-CS-Fixer is installed
  stat:
    path: "{{ user_programs_path }}/php-cs-fixer"
  register: php_cs_fixer

- name: Check PHP-CS-Fixer version
  shell: php-cs-fixer --version | awk '{print $5}'
  register: php_cs_fixer_version
  when: php_cs_fixer.stat.exists == true
  changed_when: php_cs_fixer_version.stdout != "{{ php_cs_fixer_stable_release }}"

- name: Download PHP-CS-Fixer PHAR file
  get_url:
    url: https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v{{ php_cs_fixer_stable_release }}/php-cs-fixer.phar
    dest: /tmp
    mode: 0755
    validate_certs: no
  register: php_cs_fixer_get_url_result
  until: "'OK' in php_cs_fixer_get_url_result.msg"
  retries: 3
  delay: 10
  when: php_cs_fixer.stat.exists == false or php_cs_fixer_version.stdout != "{{ php_cs_fixer_stable_release }}"

- name: Rename PHP-CS-Fixer PHAR file
  command: mv /tmp/php-cs-fixer.phar /tmp/php-cs-fixer
  when: php_cs_fixer.stat.exists == false or php_cs_fixer_version.stdout != "{{ php_cs_fixer_stable_release }}"

- name: Install PHP-CS-Fixer globally
  command: mv /tmp/php-cs-fixer {{ user_programs_path }}/
  when: php_cs_fixer.stat.exists == false or php_cs_fixer_version.stdout != "{{ php_cs_fixer_stable_release }}"
