---
- name: Check if PHP is installed
  stat:
    path: /etc/php5/fpm/php.ini
  register: fpm

- name: Prepare for PHP-FPM installation
  lineinfile:
    dest: "/etc/apt/sources.list"
    regexp: "deb http://httpredir.debian.org/debian {{ codename }} main"
    line: "deb http://httpredir.debian.org/debian {{ codename }} main contrib non-free"
  when: fpm.stat.exists == false

- name: Install PHP core packages
  package:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - php5-fpm
    - php5-cli
    - php5-common
    - php5-dev
    - libapache2-mod-fastcgi
  when: fpm.stat.exists == false

- name: Install PHP extensions
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - php5-apcu
    - php5-curl
    - php5-gd
    - php5-memcached
    - php5-mysql
    - php5-xsl
  when: fpm.stat.exists == false

- name: Deploy fastcgi.conf template
  copy:
    src: files/fastcgi.conf
    dest: /etc/apache2/mods-available/fastcgi.conf
    mode: 0644
  when: fpm.stat.exists == false

- name: Enable actions module
  apache2_module:
    state: present
    name: actions
  when: fpm.stat.exists == false

- name: Disable php5 module
  apache2_module:
    state: absent
    name: php5
  notify: Restart PHP-FPM
  when: fpm.stat.exists == true

- name: Increase max_execution_time
  lineinfile:
    dest: "/etc/php5/fpm/php.ini"
    regexp: "max_execution_time = 30"
    line: "max_execution_time = {{ max_execution_time }}"
  when: fpm.stat.exists == false

- name: Harden PHP
  lineinfile:
    dest: "/etc/php5/fpm/php.ini"
    regexp: "SSLProtocol all"
    line: "SSLProtocol all -SSLv2 -SSLv3"
  when: fpm.stat.exists == false

- name: Add default timezone
  lineinfile:
    dest: "/etc/php5/cli/php.ini"
    regexp: ";date.timezone ="
    line: "date.timezone = UTC"
  notify: Restart Apache
  when: fpm.stat.exists == false

- name: Support file upload progress through APC
  lineinfile:
    dest: /etc/php5/fpm/php.ini
    line: "apc.rfc1867 = 1"
  when: fpm.stat.exists == false

- name: Ensure Apache is restarted
  service:
    name: apache2
    enabled: yes
    state: restarted

- name: Ensure PHP-FPM is restarted
  service:
    name: php5-fpm
    enabled: yes
    state: restarted
