---
- name: Check if PHP is installed
  stat:
    path: "{{ php_ini }}"
  register: fpm

- name: Add Debian contrib and non-free repositories
  # Brings support for FastCGI via libapache2-mod-fastcgi
  lineinfile:
    dest: "{{ sources_list }}"
    regexp: "deb http://httpredir.debian.org/debian {{ codename }} main"
    line: "deb http://httpredir.debian.org/debian {{ codename }} main contrib non-free"
  when: fpm.stat.exists == false

- name: Add deb.sury.org GPG signature
  apt_key:
    url: "{{ sury_gpg }}"
    state: present
  when: fpm.stat.exists == false

- name: Add deb.sury.org repository
  apt_repository:
    repo: "{{ sury_deb }}"
    state: present
  when: fpm.stat.exists == false

- name: Install PHP core packages
  package:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - php{{ php_version }}-fpm
    - php{{ php_version }}-cli
    - php{{ php_version }}-common
    - php{{ php_version }}-dev
    - libapache2-mod-fastcgi
  when: fpm.stat.exists == false

#  php7.1-intl mcrypt

- name: Install PHP extensions
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - php{{ php_version }}-apcu
    - php{{ php_version }}-curl
    - php{{ php_version }}-gd
    - php{{ php_version }}-imagick
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-mcrypt
    - php{{ php_version }}-memcached
    - php{{ php_version }}-mysql
    - php{{ php_version }}-xmlrpc
    - php{{ php_version }}-xsl
    - php{{ php_version }}-bz2
  when: fpm.stat.exists == false

- name: Deploy fastcgi.conf template
  copy:
    src: "{{ fastcgi_source_file }}"
    dest: "{{ apache_fastcgi_conf }}"
    mode: 0644
  when: fpm.stat.exists == false

- name: Check if php 7 module is enabled
  stat:
    path: "{{ apache_php_mod }}"
  register: php7_module

- name: Disable php 7 module
  apache2_module:
    state: absent
    name: php7
  notify: Restart PHP-FPM
  when: php7_module.stat.exists == true

- name: Increase max_input_time
  lineinfile:
    dest: "{{ php_ini }}"
    regexp: "max_input_time = 60"
    line: "max_input_time = {{ max_input_time }}"
  when: fpm.stat.exists == false

- name: Increase max_execution_time
  lineinfile:
    dest: "{{ php_ini }}"
    regexp: "max_execution_time = 30"
    line: "max_execution_time = {{ max_execution_time }}"
  when: fpm.stat.exists == false

- name: Increase memory_limit
  lineinfile:
    dest: "{{ php_ini }}"
    regexp: "memory_limit = 128M"
    line: "memory_limit = {{ memory_limit }}"
  when: fpm.stat.exists == false

- name: Increase upload_max_filesize
  lineinfile:
    dest: "{{ php_ini }}"
    regexp: "upload_max_filesize = 2M"
    line: "upload_max_filesize = {{ upload_max_filesize }}"
  when: fpm.stat.exists == false

- name: Increase max_file_uploads
  lineinfile:
    dest: "{{ php_ini }}"
    regexp: "max_file_uploads = 20"
    line: "max_file_uploads = {{ max_file_uploads }}"
  when: fpm.stat.exists == false

- name: Add default timezone
  lineinfile:
    dest: "{{ php_ini_cli }}"
    regexp: ";date.timezone ="
    line: "date.timezone = {{ timezone }}"
  notify: Restart Apache
  when: fpm.stat.exists == false

- name: Ensure PHP extensions directory exists
  file:
    path: "{{ php_extensions }}"
    state: directory
  when: fpm.stat.exists == false
