---
- name: Check if PHP is installed
  stat:
    path: "{{ php_ini }}"
  register: fpm

- name: Add Debian contrib and non-free repositories
  # Brings support for FastCGI via libapache2-mod-fastcgi
  lineinfile:
    dest: "/etc/apt/sources.list"
    regexp: "deb http://httpredir.debian.org/debian {{ codename }} main"
    line: "deb http://httpredir.debian.org/debian {{ codename }} main contrib non-free"
  when: fpm.stat.exists == false

- name: Add DOTDEB repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://packages.dotdeb.org {{ codename }} all
    - deb-src http://packages.dotdeb.org {{ codename }} all
  when: fpm.stat.exists == false

- name: Add DOTDEB GPG signature
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg
    state: present
  when: fpm.stat.exists == false

- name: Install PHP core packages
  package:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - php7.0-fpm
    - php7.0-cli
    - php7.0-common
    - php7.0-dev
    - libapache2-mod-fastcgi
  when: fpm.stat.exists == false

- name: Install PHP extensions
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - php7.0-apcu
    - php7.0-curl
    - php7.0-gd
    - php7.0-memcached
    - php7.0-mysql
    - php7.0-xsl
  when: fpm.stat.exists == false

- name: Deploy fastcgi.conf template
  copy:
    src: files/fastcgi.conf
    dest: /etc/apache2/mods-available/fastcgi.conf
    mode: 0644
  when: fpm.stat.exists == false

- name: Enable actions module
  apache2_module:
    state: present
    name: actions
  when: fpm.stat.exists == false

- name: Check if php7.0 module is enabled
  stat:
    path: /etc/apache2/mods-available/php7.0.conf
  register: php7_module

- name: Disable php7.0 module
  apache2_module:
    state: absent
    name: php7
  notify: Restart PHP-FPM
  when: php7_module.stat.exists == true

- name: Increase max_input_time
  lineinfile:
    dest: "{{ php_ini }}"
    regexp: "max_input_time = 60"
    line: "max_input_time = {{ max_input_time }}"
  when: fpm.stat.exists == false

- name: Increase max_execution_time
  lineinfile:
    dest: "{{ php_ini }}"
    regexp: "max_execution_time = 30"
    line: "max_execution_time = {{ max_execution_time }}"
  when: fpm.stat.exists == false

- name: Increase memory_limit
  lineinfile:
    dest: "{{ php_ini }}"
    regexp: "memory_limit = 128M"
    line: "memory_limit = {{ memory_limit }}"
  when: fpm.stat.exists == false

# - name: Harden PHP
#   lineinfile:
#     dest: "{{ php_ini }}"
#     regexp: "SSLProtocol all"
#     line: "SSLProtocol all -SSLv2 -SSLv3"
#   when: fpm.stat.exists == false

- name: Add default timezone
  lineinfile:
    dest: "{{ php_ini_cli }}"
    regexp: ";date.timezone ="
    line: "date.timezone = UTC"
  notify: Restart Apache
  when: fpm.stat.exists == false

- name: Ensure PHP extensions directory exists
  file:
    path: "{{ php_extensions }}"
    state: directory
  when: fpm.stat.exists == false
