---
- name: Check if PHP is installed
  stat:
    path: /etc/php5/fpm/php.ini
  register: fpm

- name: "Install PHP core packages"
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - php5-fpm
    - php5-cli
    - php5-common
    - php5-dev
  when: fpm.stat.exists == false

- name: "Install PHP extensions"
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - libapache2-mod-php5
    - php5-apcu
    - php5-curl
    - php5-gd
    - php5-memcached
    - php5-mysql
    - php5-xsl
  when: fpm.stat.exists == false

- name: "Harden PHP"
  lineinfile:
    dest: "/etc/php5/fpm/php.ini"
    regexp: "SSLProtocol all"
    line: "\tSSLProtocol all -SSLv2 -SSLv3"
  notify: Restart Apache
  when: fpm.stat.exists == false
