---
- name: Check if phpmd is installed
  stat:
    path: "{{ user_programs_path }}/phpmd"
  register: phpmd

- name: Check phpmd version
  shell: phpmd --version | awk '{print $NF}'
  register: phpmd_stable_release_check
  when: phpmd.stat.exists == true
  changed_when: phpmd_stable_release_check.stdout != "{{ phpmd_stable_version }}"

- name: Install phpmd globally
  get_url:
    url: http://static.phpmd.org/php/{{ phpmd_stable_version }}/phpmd.phar
    dest: "{{ user_programs_path }}/phpmd"
    mode: 0755
    validate_certs: no
  register: phpmd_get_url_result
  until: "'OK' in phpmd_get_url_result.msg"
  retries: 3
  delay: 10
  when: phpmd.stat.exists == false or phpmd_stable_release_check.stdout != "{{ phpmd_stable_version }}"

- name: Check if phpmd bash alias exists
  shell: egrep -o 'MANAGED PHPMD BLOCK' /home/{{ user }}/.bashrc || echo "absent"
  register: phpmd_alias
  changed_when: phpmd_alias == "absent"

- name: Add phpmd alias
  blockinfile:
    dest: /home/{{ user }}/.bashrc
    block: |
      function phpmd { /usr/local/bin/phpmd "$1" text cleancode,codesize,controversial,design,naming,unusedcode; }
      export -f phpmd
    insertafter: EOF
    marker: "# {mark} MANAGED PHPMD BLOCK"
  when: phpmd_alias.stdout == 'absent'
