---
- name: Check if Solr core exists
  stat:
    path: "{{ solr_configuration_path }}"
  register: solr_core_check
  changed_when: solr_core_check.stat.exists == false

- name: Start Solr
  shell: "{{ solr_binary }} start"
  become: yes
  become_user: solr
  when: solr_core_check.stat.exists == false

- name: Create Solr core
  shell: "{{ solr_binary }} create_core -c {{ solr_core }}"
  become: yes
  become_user: solr
  when: solr_core_check.stat.exists == false

- name: Check if the Apache Solr schema.xml file exists
  stat:
    path: "{{ solr_configuration_path }}/schema.xml"
  register: schemaxml_check
  changed_when: schemaxml_check.stat.exists == false

- name: Check if Apache Solr has been configured for Search API Solr
  shell: grep -o "search_api" {{ solr_configuration_path }}/schema.xml | head -n1 || echo "missing"
  register: solr_conf_files
  when: schemaxml_check.stat.exists == true
  changed_when: solr_conf_files.stdout != "search_api"

- name: Deploy Solr conf files
  copy:
    src: "{{ solr_conf }}"
    dest: "{{ solr_configuration_path }}"
    mode: 0644
  become: yes
  become_user: solr
  when: schemaxml_check.stat.exists == false or (solr_conf_files is defined and solr_conf_files.stdout != "search_api")

- name: Restart Solr
  shell: "{{ solr_binary }} restart"
  become: yes
  become_user: solr
