---
# Allows Drush to bootstrap a remote DB.
- name: Check if SSH key exists
  stat:
    path: /home/{{ user }}/.ssh/id_rsa
  register: rsa_web
  ignore_errors: True

- name: Generate SSH keys for remote MySQL access
  shell: ssh-keygen -b 4096 -t rsa -f /home/{{ user }}/.ssh/id_rsa -q -N ""
  args:
    creates: /home/{{ user }}/.ssh/id_rsa
  when: rsa_web.stat.exists == false

- name: Make sure permissions are correct on SSH keys
  file:
    path: /home/{{ user }}/.ssh/{{ item }}
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - id_rsa
    - id_rsa.pub
  when: rsa_web.stat.exists == false
