---
- name: Clean up system packages
  package:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
  - vim-tiny

- name: Install system packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - ack-grep
  - curl
  - dstat
  - git
  - htop
  - iputils-ping
  # phantomjs secret dependency
  - libfontconfig1
  - logrotate
  - ncdu
  - netcat
  - net-tools
  - ntp
  - patchutils
  - strace
  - sysstat
  - time
  - vim
  - wget

- name: Ensure NTP is running
  service:
    name: ntp
    state: started
    enabled: yes

- name: Check if .bash_aliases exist
  stat:
    path: "{{ bash_aliases }}"
  register: bash_aliases

- name: Deploy .bash_aliases
  copy:
    src: "{{ bash_aliases_source_file}}"
    dest: "{{ home }}"
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"
  become: yes
  become_user: "{{ user }}"
  when: bash_aliases.stat.exists == false

- name: Check if .vimrc file exists
  stat:
    path: "{{ vimrc }}"
  register: vimrc
  ignore_errors: True

- name: Deploy .vimrc file
  copy:
    src: "{{ vimrc_source_file }}"
    dest: "{{ home }}"
    mode: 0644
  become: yes
  become_user: "{{ user }}"
  when: vimrc.stat.exists == false

- name: Check if .vim directory exists
  stat:
    path: "{{ vim_dir }}"
  register: vim_dir
  ignore_errors: True

- name: Deploy .vim directory
  copy:
    src: "{{ vim_source_dir }}"
    dest: "{{ home }}"
    mode: 0755
  become: yes
  become_user: "{{ user }}"
  when: vim_dir.stat.exists == false
