---
- name: Clean up system packages
  package:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
  - vim-tiny

- name: Install system packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - ack-grep
  - curl
  - dstat
  - git
  - htop
  - iputils-ping
  - logrotate
  - ncdu
  - netcat
  - net-tools
  - ntp
  - patchutils
  - strace
  - sysstat
  - vim
  - wget

- name: Ensure NTP is running
  service:
    name: ntp
    state: started
    enabled: yes

- name: Check if .bash_aliases exist
  stat:
    path: /home/{{ user }}/.bash_aliases
  register: bash_aliases

- name: Deploy .bash_aliases
  copy:
    src: files/.bash_aliases
    dest: /home/{{ user }}/
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"
  when: bash_aliases.stat.exists == false
