---
- name: Clean up system packages
  package:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
  - vim-tiny

- name: Install system packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - ack-grep
  - curl
  - dstat
  - git
  - htop
  - iputils-ping
  # phantomjs secret dependency
  - libfontconfig1
  - logrotate
  - ncdu
  - netcat
  - net-tools
  - ntp
  - patchutils
  - strace
  - sysstat
  - time
  - vim
  - wget

- name: Ensure NTP is running
  service:
    name: ntp
    state: started
    enabled: yes

- name: Check if .bash_aliases exist
  stat:
    path: "{{ home }}/.bash_aliases"
  register: bash_aliases

- name: Deploy .bash_aliases
  copy:
    src: files/.bash_aliases
    dest: "{{ home }}"
    mode: 0644
    owner: "{{ user }}"
    group: "{{ user }}"
  when: bash_aliases.stat.exists == false

- name: Check if .vimrc file exists
  stat:
    path: "{{ home }}/.vimrc"
  register: vimrc
  ignore_errors: True

- name: Deploy .vimrc file
  copy:
    src: files/.vimrc
    dest: "{{ home }}"
    mode: 0644
  when: vimrc.stat.exists == false

- name: Check if .vim directory exists
  stat:
    path: "{{ home }}/.vim"
  register: vim
  ignore_errors: True

- name: Deploy .vim directory
  copy:
    src: files/.vim
    dest: "{{ home }}"
    mode: 0755
  when: vim.stat.exists == false

- name: Make sure permissions are correct for Vim configuration files
  file:
    path: "{{ home }}/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - .vimrc
    - .vim
  when: vim.stat.exists == false
