---
- name: Clean up system packages
  package:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
  - vim-tiny

- name: Install system packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - ack-grep
  - git
  - ncdu
  - vim
  - wget
  - strace
  - sysstat
  - dstat
  - netcat
  - net-tools
  - ntp
  - iputils-ping
  - logrotate
  - htop

- name: Ensure NTP is running
  service:
    name: ntp
    state: started
    enabled: yes
