---
- name: Check if Varnish has been installed
  stat:
    path: "{{ varnish_config }}"
  register: varnish
  ignore_errors: True

- name: Prepare for Varnish installation 1/3
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
  when: varnish.stat.exists == false

- name: Prepare for Varnish installation 2/3
  apt_key:
    url: "{{ varnish_gpg_key }}"
    state: present
  when: varnish.stat.exists == false

- name: Prepare for Varnish installation 3/3
  apt_repository:
    repo: "{{ varnish_deb }}"
    state: present
  when: varnish.stat.exists == false

- name: Install Varnish
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - varnish
  when: varnish.stat.exists == false

- name: Deploy Varnish template
  copy:
    src: "{{ varnish_conf_source_file }}"
    dest: /etc/default/
    mode: 0644
  when: varnish.stat.exists == false

- name: "Deploy Varnish's default VCL template"
  copy:
    src: "{{ varnish_default_vcl_source_file}}"
    dest: "{{ varnish_default_path }}"
    mode: 0644
  when: varnish.stat.exists == false

- name: Ensure Varnish is started
  service:
    name: varnish
    enabled: yes
    state: started
