---
- name: Check if Varnish has been installed
  stat:
    path: "{{ varnish_config }}"
  register: varnish
  ignore_errors: True

- name: Prepare for Varnish installation 1/3
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
  when: varnish.stat.exists == false

- name: Prepare for Varnish installation 2/3
  apt_key:
    url: https://repo.varnish-cache.org/GPG-key.txt
    state: present
  when: varnish.stat.exists == false

- name: Prepare for Varnish installation 3/3
  apt_repository:
    repo: 'deb https://repo.varnish-cache.org/debian/ {{ codename }} varnish-{{ varnish_source }}'
    state: present
  when: varnish.stat.exists == false

- name: Install Varnish
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - varnish
  when: varnish.stat.exists == false

- name: Deploy Varnish template
  copy:
    src: files/varnish
    dest: /etc/default/
    mode: 0644
  when: varnish.stat.exists == false

- name: "Deploy Varnish's default VCL template"
  copy:
    src: files/default.vcl
    dest: "{{ varnish_default_path }}"
    mode: 0644
  when: varnish.stat.exists == false

- name: Ensure Varnish is started
  service:
    name: varnish
    enabled: yes
    state: started
