---
- name: "TEST: Drupal needs to be correctly installed"
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ docroot }}"
    - "{{ files_dir }}"
    - "{{ libraries_dir }}"
    - "{{ settings_php }}"
    - "{{ services_yml }}"
    - "{{ simpletest_dir }}"
    - "{{ drupal_git }}"
    - "{{ drupal_gitignore }}"
    - "{{ mysql_data }}/{{ user }}"
    - "{{ drucker_vhost }}"
    - "{{ drucker_aliases }}"
    - "{{ phpunit_xml }}"
    - "{{ import_dir }}"
    - "{{ archives_dir }}"
    - "{{ drupal_git_clone_path }}"
  register: drupal
  failed_when: drupal.stat.exists == false

- name: "TEST: settings.php should hold the correct trusted_host_patterns setting"
  shell: grep -F "{{ user }}\.{{ tld }}" {{ settings_php }} || echo "missing"
  register: trusted_host_patterns
  changed_when: trusted_host_patterns.stdout == "missing"
  failed_when: trusted_host_patterns.stdout == "missing"

- name: Retrieve path to sync directory
  shell: stat -c %n {{ files_dir }}/config_*/sync
  register: sync_dir_test
  changed_when: sync_dir_test is undefined
  failed_when: sync_dir_test is undefined

- name: "TEST: The sync directory should be writable"
  stat:
    path: "{{ sync_dir_test.stdout }}"
  register: writable_sync
  changed_when: writable_sync.stat.mode != "0777"
  failed_when: writable_sync.stat.mode != "0777"

- name: "TEST: Make sure the codebase was added under version control"
  shell: git -C {{ docroot }} log --oneline | grep -o "Initial commit" || echo 'no commit'
  args:
    warn: no
  register: initial_commit
  changed_when: initial_commit == "no commit"
  failed_when: initial_commit == "no commit"

- name: "TEST: Ensure remote MySQL databases can be managed"
  shell: dpkg -l | grep "python-mysqldb"
  register: remote_db_management
  changed_when: remote_db_management == ''

- name: "TEST: Ensure Drupal can talk to the Solr backend"
  shell: grep -o "{{ search_ip }}" {{ hosts_file }} || echo "absent"
  register: search_hostname_check
  changed_when: search_hostname_check == "absent"
  failed_when: search_hostname_check == "absent"
