---
- hosts: drucker_base
  sudo: yes

  gather_facts: no
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  roles:
    - yaegashi.blockinfile
  tasks:
    - include: playbooks/ssh.yml tags=ssh
    - include: playbooks/system.yml tags=system
