---
- hosts: drucker_base
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  tasks:
    - include: playbooks/system/ssh.yml
    - include: playbooks/system/system-setup.yml
    - include: playbooks/system/git.yml
