---
- hosts: drucker_base
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  tasks:
    - include: playbooks/ssh.yml
    - include: playbooks/system.yml
