---
- hosts: drucker_db
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  tasks:
    - include: playbooks/common/mirror-deploy.yml
    - include: playbooks/db/mysql.yml
    - include: playbooks/db/memcached.yml
    - include: playbooks/db/mysql-backup.yml
