---
- hosts: drucker_db
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  roles:
    - geerlingguy.mysql
  tasks:
    - include: playbooks/mysql.yml
    - include: playbooks/mysql-backup.yml
