---
- hosts: drucker_web2
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  tasks:
    - include: playbooks/gluster/gluster-setup.yml

- hosts: drucker_web
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  tasks:
    - include: playbooks/gluster/gluster-setup.yml
