---
- hosts: drucker_gluster
  become: yes

  gather_facts: no
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  roles:
    - yaegashi.blockinfile
  tasks:
    - include: playbooks/gluster.yml
