---
- hosts: drucker_mirror
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  tasks:
    - include: playbooks/common/apache-installation.yml
    - include: playbooks/mirror/mirror-vhost.yml
    - include: playbooks/common/apt-repos.yml
    - include: playbooks/common/mirror-downloads.yml
    - include: playbooks/mirror-setup.yml
