---
# Invoked via run_tests() in containers/orchestration.
- hosts: drucker_mirror
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  tasks:
    - include: playbooks/_tests/run-mirror-tests.yml
