---
- hosts: drucker_reverse_proxy
  sudo: yes

  gather_facts: no
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  roles:
    - yaegashi.blockinfile
  tasks:
    - include: playbooks/varnish.yml tags=varnish
    - include: playbooks/nginx.yml tags=nginx
