---
# Invoked via run_tests() in containers/orchestration.
- hosts: drucker_reverse_proxy
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  tasks:
    - include: playbooks/tests/run-reverse-proxy-tests.yml
