---
- hosts: drucker_reverse_proxy
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  tasks:
    - include: playbooks/varnish.yml
    - include: playbooks/nginx.yml
