---
- hosts: drucker_reverse_proxy
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  tasks:
    - include: playbooks/common/mirror-deploy.yml
    - include: playbooks/common/apt-update.yml
    - include: playbooks/proxy/varnish.yml
    - include: playbooks/proxy/nginx.yml
