---
- hosts: drucker_search
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  roles:
    - williamyeh.oracle-java
    - geerlingguy.solr
  tasks:
    - include: playbooks/solr-configuration.yml
