---
- hosts: drucker_web
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  roles:
    - yaegashi.blockinfile
  tasks:
    - include: playbooks/apache.yml
    - include: playbooks/php.yml
    - include: playbooks/xdebug.yml
    - include: playbooks/codesniffer.yml
    - include: playbooks/composer.yml
    - include: playbooks/mysql.yml
    - include: playbooks/phpmyadmin.yml
    - include: playbooks/adminer.yml
    - include: playbooks/drush.yml
    - include: playbooks/drupal-console.yml
    - include: playbooks/drupal.yml
    # - include: playbooks/gluster.yml
