---
- hosts: drucker_web
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - include: handlers.yml
  tasks:
    - include: playbooks/ssh-keys.yml
    - include: playbooks/apache.yml
    - include: playbooks/php.yml
    - include: playbooks/composer.yml
    - include: playbooks/phpmyadmin.yml
    - include: playbooks/adminer.yml
    - include: playbooks/drush.yml
    - include: playbooks/drupal-console.yml
    - include: playbooks/uploadprogress.yml
    - include: playbooks/xdebug.yml
    - include: playbooks/tideways.yml
    - include: playbooks/phantomjs.yml
    - include: playbooks/codesniffer.yml
    - include: playbooks/php-cs-fixer.yml
    - include: playbooks/coder.yml
    - include: playbooks/phpmd.yml
    - include: playbooks/drupal-reinstall.yml
      when: reinstall == "Y"
    - include: playbooks/drupal-delete.yml
      when: delete == "Y"
    - include: playbooks/drupal.yml
    - include: playbooks/drupal-dev.yml
      when: dev == "Y"
    - include: playbooks/drupal-prod.yml
      when: prod == "Y"
    - include: playbooks/drupal-import.yml
      when: import == "Y"
    - include: playbooks/tests/tests.yml
      when: tests == "Y"
    # - include: playbooks/gluster.yml
