---
- hosts: drucker_web
  become: yes

  gather_facts: yes
  vars_files:
    - vars.yml
  handlers:
    - import_tasks: handlers.yml
  tasks:
    - import_tasks: playbooks/common/mirror-deploy.yml
    - import_tasks: playbooks/common/apt-update.yml
    - import_tasks: playbooks/stack.yml
    - import_tasks: playbooks/drupal.yml
    - import_tasks: playbooks/post-install.yml
