---
- name: "IMPORT: Check if MySQL dump exists"
  stat:
    path: "{{ item }}"
  with_first_found:
    - files:
      - "{{ import_sqlgz }}"
      - "{{ import_sql }}"
      skip: true
  register: dump_detection
  ignore_errors: True

- set_fact:
    dump: "{{ dump_detection.results[0]['item'] }}"
  when: dump_detection.skipped is not defined

- name: "IMPORT: Create new database"
  mysql_db:
    login_user: "{{ mysql_creds }}"
    login_password: "{{ mysql_creds }}"
    login_host: "{{ db_ip }}"
    login_port: "{{ mysql_port }}"
    config_file: "{{ my_cnf }}"
    name: "{{ sitename }}"
    state: present
  when: dump_detection.skipped is not defined

- name: "IMPORT: Restore MySQL dump"
  mysql_db:
    login_user: "{{ mysql_creds }}"
    login_password: "{{ mysql_creds }}"
    login_host: "{{ db_ip }}"
    login_port: "{{ mysql_port }}"
    config_file: "{{ my_cnf }}"
    name: "{{ sitename }}"
    state: import
    target: "{{ dump }}"
  when: dump_detection.skipped is not defined

- name: "IMPORT: Check if archived database dump exists"
  stat:
    path: "{{ import_archive_path }}"
  register: db_archive
  ignore_errors: True

- name: "IMPORT: Archive imported database dump"
  command: mv {{ dump }} {{ archives_dir }}
  when: dump_detection.skipped is not defined and db_archive.stat.exists == false

- name: "IMPORT: Check if docroot has already been deployed"
  stat:
    path: "{{ imported_docroot }}"
  register: docroot_check
  ignore_errors: True

- name: "IMPORT: Check if docroot exists"
  stat:
    path: "{{ import_sitename_path }}"
  register: docroot_import
  ignore_errors: True

- name: "IMPORT: Import docroot"
  command: cp -R {{ import_sitename_path }} {{ webroot }}
  register: import_docroot
  when: docroot_check.stat.exists == false and docroot_import.stat.exists == true

- name: "IMPORT: Check if archived docroot exists"
  stat:
    path: "{{ import_archive_path }}"
  register: docroot_archive
  ignore_errors: True

- name: "IMPORT: Archive imported docroot"
  command: mv {{ import_sitename_path }} {{ archives_dir }}
  when: docroot_archive.stat.exists == false

- name: "IMPORT: Make sure permissions are correct"
  file:
    path: "{{ imported_docroot }}"
    owner: "{{ user }}"
    group: "{{ apache_user }}"
    recurse: yes
  when: docroot_check.stat.exists == false and docroot_import.stat.exists == true

- name: "IMPORT: Check if vHost exists"
  stat:
    path: "{{ imported_site_vhost }}"
  register: apache_conf
  ignore_errors: True

- name: "IMPORT: Deploy default vHost template"
  copy:
    src: "{{ apache_template_source_file }}"
    dest: "{{ sites_available }}"
    mode: 0644
  when: apache_conf.stat.exists == false

- name: "IMPORT: Rename default vHost template"
  command: mv {{ vhost_template }} {{ imported_site_available_vhost }}
  when: apache_conf.stat.exists == false

- name: "IMPORT: Modify vHost"
  replace:
    dest: "{{ imported_site_available_vhost }}"
    regexp: '^(.*)SITENAME(.*)$'
    replace: '\1{{ sitename }}\2'
  when: apache_conf.stat.exists == false

- name: "IMPORT: Enable vHost"
  file:
    src: ../sites-available/{{ sitename }}.conf
    dest: "{{ imported_site_vhost }}"
    state: link
  notify: Reload Apache
  when: apache_conf.stat.exists == false

- name: "IMPORT: Check if Drush aliases exist"
  stat:
    path: "{{ imported_site_aliases }}"
  register: sitename_aliases

- name: "IMPORT: Deploy Drush aliases"
  copy:
    src: "{{ drush_aliases_source_file }}"
    dest: "{{ imported_site_aliases }}"
    mode: 0644
  when: sitename_aliases.stat.exists == false

- name: "IMPORT: Update Drush aliases"
  replace:
    dest: "{{ imported_site_aliases }}"
    regexp: '^(.*)SITENAME(.*)$'
    replace: '\1{{ sitename }}\2'
  when: sitename_aliases.stat.exists == false

- name: "IMPORT: Check if default settings.php exists"
  stat:
    path: "{{ imported_docroot }}/{{ default_site }}/settings.php"
  register: default_settings

- name: "IMPORT: Allow new site to connect to remote MySQL"
  blockinfile:
    dest: "{{ imported_docroot }}/{{ default_site }}/settings.php"
    block: |
      $databases['default']['default'] = [
        'database' => '{{ sitename }}',
        'username' => '{{ mysql_creds }}',
        'password' => '{{ mysql_creds }}',
        'prefix' => '',
        'host' => '{{ db_ip }}',
        'port' => '{{ mysql_port }}',
        'driver' => 'mysql',
      ];
    insertafter: EOF
    marker: "# {mark} MANAGED REMOTE MYSQL CONNECTION BLOCK"
  when: default_settings.stat.exists == true
