---
- name: "CREATE: Check if new site exists"
  stat:
    path: "{{ drupal_root }}"
  register: new_site
  ignore_errors: True

- name: "CREATE: Check if new database exists"
  stat:
    path: "{{ db_data }}/{{ sitename }}"
  register: new_db

- name: "CREATE: Create new site architecture"
  file:
    path: "{{ drupal_root }}"
    state: directory
  become: yes
  become_user: "{{ user }}"
  when: new_site.stat.exists == false

- name: "CREATE: Deploy default composer.json template"
  copy:
    src: "{{ composer_json_template_file }}"
    dest: "{{ drupal_root }}"
    mode: 0644
  become: yes
  become_user: "{{ user }}"
  when: new_site.stat.exists == false

- name: "CREATE: Rename composer-template.json filename"
  command: mv {{ drupal_root }}/composer-template.json {{ drupal_root }}/composer.json
  when: new_site.stat.exists == false

- name: "CREATE: Install vendor dependencies from composer.json file (this can take a while)"
  composer:
    command: install
    working_dir: "{{ drupal_root }}"
  become: yes
  become_user: "{{ user }}"

- import_tasks: ../common/drupal-common.yml

- name: "CREATE: Install Drupal"
  command: drush --root={{ drupal_root }} site-install standard install_configure_form.enable_update_status_module=NULL -qy --db-url=mysql://{{ db_creds }}:{{ db_creds }}@{{ db_ip }}:{{ db_port }}/{{ sitename }} --site-name={{ sitename }} --site-mail={{ drupal_creds }}@{{ sitename }}.{{ tld }} --account-name={{ drupal_creds }} --account-pass={{ drupal_creds }} --account-mail={{ drupal_creds }}@{{ sitename }}.{{ tld }}
  become: yes
  become_user: "{{ user }}"
  when: new_alias.stat.exists == false

- name: "CREATE: Check if phpunit.xml file exists"
  stat:
    path: "{{ drupal_docroot }}/core/phpunit.xml"
  register: phpunit_check

- name: "CREATE: Deploy phpunit.xml file"
  copy:
    src: "{{ phpunit_source_file }}"
    dest: "{{ drupal_docroot }}/core/"
    mode: 0644
  become: yes
  become_user: "{{ user }}"
  when: phpunit_check.stat.exists == false

- name: "CREATE: Modify phpunit.xml file"
  replace:
    dest: "{{ drupal_docroot }}/core/phpunit.xml"
    regexp: '^(.*)SITENAME(.*)$'
    replace: '\1{{ sitename }}\2'
  when: phpunit_check.stat.exists == false

- name: "CREATE: Check if .gitignore exists"
  stat:
    path: "{{ drupal_root }}/.gitignore"
  register: gitignore_check
  ignore_errors: True

- name: "CREATE: Create .gitignore file"
  copy:
    src: "{{ gitignore_source_file }}"
    dest: "{{ drupal_root }}"
    mode: 0644
  become: yes
  become_user: "{{ user }}"
  when: gitignore_check.stat.exists == false

- name: "CREATE: Initialize Git repository"
  shell: git -C {{ drupal_root }} init
  args:
    warn: no
  register: initial_commit
  become: yes
  become_user: "{{ user }}"
  when: gitignore_check.stat.exists == false

- name: "CREATE: Add all new files under version control"
  shell: git -C {{ drupal_root }} add --all . && git -C {{ drupal_root }} commit -m "Initial commit"
  become: yes
  become_user: "{{ user }}"
  when: gitignore_check.stat.exists == false

- name: "CREATE: Make sure files dir ownership is correct"
  file:
    path: "{{ drupal_docroot }}/{{ default_site }}/files"
    owner: "{{ user }}"
    group: "{{ apache_user }}"
    recurse: yes
  when: new_site.stat.exists == false or new_db.stat.exists == false
