---
- name: Check if repo directory exists
  stat:
    path: "{{ git_repo_directory }}"
  register: git_repo_dir
  ignore_errors: True

- name: Create repo directory
  file:
    path: "{{ git_repo_directory }}"
    state: directory
  become: yes
  become_user: "{{ user }}"
  when: git_repo_dir.stat.exists == false

- name: Check if Drupal clone exists
  stat:
    path: "{{ drupal_git_clone_path }}"
  register: git_clone_dir
  ignore_errors: True

- name: Copy Drupal repository from mirror
  shell: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r {{ mirror_ip }}:{{ git_repo_mirror_directory }} {{ drupal_git_clone_path }}
  become: yes
  become_user: "{{ user }}"
  when: git_clone_dir.stat.exists == false
