---
- name: "PROD: Disable settings.local.php"
  blockinfile:
    dest: "{{ deployed_settings_php }}"
    block: |
      if (file_exists(__DIR__ . '/settings.local.php')) {
        include __DIR__ . '/settings.local.php';
      }

    state: absent
    marker: "# {mark} MANAGED SETTINGS.LOCAL.PHP BLOCK"

- name: "PROD: Check if services.yml exists"
  stat:
    path: "{{ deployed_services_yml }}"
  register: deployed_services_yml_prod
  ignore_errors: True

- name: "PROD: Turn off Twig debugging"
  replace:
    dest: "{{ deployed_services_yml }}"
    regexp: '^(.*)    debug: true(.*)$'
    replace: '\1    debug: false\2'
  register: turn_off_twig_debugging
  when: deployed_services_yml_prod.stat.exists == true

- name: "PROD: Turn off Twig auto_reload"
  replace:
    dest: "{{ deployed_services_yml }}"
    regexp: '^(.*)    auto_reload: true(.*)$'
    replace: '\1    auto_reload: null\2'
  when: deployed_services_yml_prod.stat.exists == true

- name: "PROD: Turn on Twig caching"
  replace:
    dest: "{{ deployed_services_yml }}"
    regexp: '^(.*)    cache: false(.*)$'
    replace: '\1    cache: true\2'
  when: deployed_services_yml_prod.stat.exists == true

- name: "PROD: Check if the Testing module is installed"
  shell: drush --root={{ drupal_root }} pm-list --type=module --status=enabled | grep simpletest | awk '{print $4}'
  register: testing_module_check

- name: "PROD: Uninstall the Testing module"
  command: drush --root={{ drupal_root }} pm-uninstall -y simpletest
  when: testing_module_check.stdout == "Enabled"

- name: "PROD: Rebuild Drupal cache"
  command: drush --root={{ drupal_root }} cache-rebuild
  when: turn_off_twig_debugging.changed

- name: "PROD: Check the Zend assertions status"
  shell: grep "^zend.assertions = 1" "{{ default_php_ini }}" || echo "off"
  register: zend_assertions_disable
  changed_when: zend_assertions_disable.stdout != "off"

- name: "PROD: Turn off Zend assertions"
  replace:
    dest: "{{ default_php_ini }}"
    regexp: '^(.*)zend.assertions = 1(.*)$'
    replace: '\1zend.assertions = -1\2'
  notify: Restart Apache
  when: zend_assertions_disable.stdout != "off"
