---
- name: "COMPOSER: Check if composer.json exists"
  stat:
    path: "{{ composer_json_expected_filename }}"
  register: composer_webroot
  ignore_errors: True

- name: "COMPOSER: Deploy default composer.json template"
  copy:
    src: "{{ composer_json_template_file }}"
    dest: "{{ webroot }}"
    mode: 0644
  become: yes
  become_user: "{{ user }}"
  when: composer_webroot.stat.exists == false

- name: "COMPOSER: Rename composer-template.json filename"
  command: mv {{ composer_json_template_temp_filename }} {{ composer_json_expected_filename }}
  when: composer_webroot.stat.exists == false

- name: "COMPOSER: Check if new site exists"
  stat:
    path: "{{ drupal_root }}"
  register: new_site
  ignore_errors: True

- name: "COMPOSER: Check if new database exists"
  stat:
    path: "{{ db_data }}/{{ sitename }}"
  register: new_db

- name: "COMPOSER: Create new site architecture"
  file:
    path: "{{ drupal_root }}"
    state: directory
  become: yes
  become_user: "{{ user }}"
  when: new_site.stat.exists == false

- name: "COMPOSER: Move composer.json file into new docroot"
  command: mv {{ composer_json_expected_filename }} {{ drupal_root }}
  when: new_site.stat.exists == false

- name: "COMPOSER: Install vendor dependencies from composer.json file (this can take a while)"
  composer:
    command: install
    working_dir: "{{ drupal_root }}"
  become: yes
  become_user: "{{ user }}"

- include: ../common/drupal-common.yml

- name: "COMPOSER: Install Drupal"
  command: drush @{{ sitename }}.{{ tld }} site-install standard install_configure_form.update_status_module='array(FALSE,FALSE)' -qy --db-url=mysql://{{ db_creds }}:{{ db_creds }}@{{ db_ip }}:{{ db_port }}/{{ sitename }} --site-name={{ sitename }} --site-mail={{ drupal_creds }}@{{ sitename }}.{{ tld }} --account-name={{ drupal_creds }} --account-pass={{ drupal_creds }} --account-mail={{ drupal_creds }}@{{ sitename }}.{{ tld }}
  become: yes
  become_user: "{{ user }}"
  when: new_aliases.stat.exists == false

- name: "COMPOSER: Check if phpunit.xml file exists"
  stat:
    path: "{{ drupal_root }}/docroot/core/phpunit.xml"
  register: composer_phpunit

- name: "COMPOSER: Deploy phpunit.xml file"
  copy:
    src: "{{ phpunit_source_file }}"
    dest: "{{ drupal_root }}/docroot/core/"
    mode: 0644
  become: yes
  become_user: "{{ user }}"
  when: composer_phpunit.stat.exists == false

- name: "COMPOSER: Modify phpunit.xml file"
  replace:
    dest: "{{ drupal_root }}/docroot/core/phpunit.xml"
    regexp: '^(.*)SITENAME(.*)$'
    replace: '\1{{ sitename }}\2'
  when: composer_phpunit.stat.exists == false

- name: "COMPOSER: Make sure we're down one level for the PHPUnit path"
  replace:
    dest: "{{ drupal_root }}/docroot/core/phpunit.xml"
    regexp: '^(.*){{ drupal_root }}(.*)$'
    replace: '\1{{ drupal_root }}/docroot\2'
  when: composer_phpunit.stat.exists == false

- name: "COMPOSER: Check if .gitignore exists"
  stat:
    path: "{{ drupal_root }}/.gitignore"
  register: composer_gitignore
  ignore_errors: True

- name: "COMPOSER: Create .gitignore file"
  copy:
    src: "{{ gitignore_source_file }}"
    dest: "{{ drupal_root }}"
    mode: 0644
  become: yes
  become_user: "{{ user }}"
  when: composer_gitignore.stat.exists == false

- name: "COMPOSER: Initialize Git repository"
  shell: git -C {{ drupal_root }} init
  args:
    warn: no
  register: initial_commit
  become: yes
  become_user: "{{ user }}"
  when: composer_gitignore.stat.exists == false

- name: "COMPOSER: Add all new files under version control"
  shell: git -C {{ drupal_root }} add --all . && git -C {{ drupal_root }} commit -m "Initial commit"
  become: yes
  become_user: "{{ user }}"
  when: composer_gitignore.stat.exists == false

- name: "COMPOSER: Make sure files dir ownership is correct"
  file:
    path: "{{ drupal_root }}/{{ default_site }}/files"
    owner: "{{ user }}"
    group: "{{ apache_user }}"
    recurse: yes
  when: new_site.stat.exists == false or new_db.stat.exists == false
